export const ERROR_CODES: Record<string, string> = {
  ERR_REQUIRE_ESM: 'require() of an ES module. Use import / dynamic import(), switch the file to ESM ("type": "module" or .mjs), or pin an older CJS version of the package.',
  ERR_MODULE_NOT_FOUND: 'ESM import could not be resolved. ESM needs full relative paths with extensions (./util.js) and the package must be installed.',
  MODULE_NOT_FOUND: 'require() could not find the module. Check the path, spelling, and that the package is installed in dependencies.',
  ERR_UNKNOWN_FILE_EXTENSION: 'Node cannot run this extension directly (often .ts). Use tsx/ts-node, compile first, or Node >= 22.6 with --experimental-strip-types.',
  ERR_PACKAGE_PATH_NOT_EXPORTED: 'Importing a subpath that the package "exports" field does not expose. Import the public entry point instead.',
  ERR_HTTP_HEADERS_SENT: 'Response headers were already sent, usually res.send/res.json called twice. Return after sending, and check async branches.',
  ERR_INVALID_ARG_TYPE: 'A Node API received the wrong type (often undefined). Validate the value before the call.',
  ERR_UNHANDLED_REJECTION: 'A promise rejected with no handler. Add await inside try/catch or a .catch().',
  ERR_OSSL_EVP_UNSUPPORTED: 'OpenSSL 3 rejected a legacy algorithm, common with old webpack. Upgrade the tool, or use NODE_OPTIONS=--openssl-legacy-provider as a temporary workaround.',
  ERR_INVALID_URL: 'new URL() received a relative or malformed string. Provide an absolute URL or a base argument.',
  ERR_STREAM_PREMATURE_CLOSE: 'A stream closed before finishing. Use stream.pipeline() and handle errors on both ends.',
  ERR_SOCKET_CONNECTION_TIMEOUT: 'Socket connect timed out. Check the host/port, firewall, and the timeout settings.',
  EADDRINUSE: 'The port is already taken by another process. Stop it, or use a different PORT.',
  ECONNREFUSED: 'Nothing is listening at the target host:port (DB/API down or wrong address). Start the service or fix the connection config; in Docker use the service name instead of localhost.',
  ECONNRESET: 'The peer closed the connection abruptly. Add retries/timeouts and check the server and proxy logs.',
  ENOTFOUND: 'DNS lookup failed. Check the hostname and the network.',
  ETIMEDOUT: 'The operation timed out. Check network reachability and timeouts.',
  ENOENT: 'File or directory does not exist. Resolve paths from import.meta.dirname / __dirname, not from process.cwd().',
  EACCES: 'Permission denied. Check file permissions; ports < 1024 need elevated rights.',
  EPERM: 'Operation not permitted, often a file locked by another process on Windows or missing rights.',
  EMFILE: 'Too many open files. Close handles, limit concurrency, or use graceful-fs.',
  TS2304: 'Cannot find name: the identifier is not declared or imported. Import it, or install its @types package.',
  TS2307: 'Cannot find module: the path or package does not resolve, or it has no types. Fix the path, install the package, or add @types / a declaration.',
  TS2322: 'Type is not assignable: the value does not match the declared type. Fix the value or widen the type deliberately.',
  TS2339: 'Property does not exist on type: TypeScript does not know about the property. Fix the name, narrow the type, or extend the type definition.',
  TS2345: 'Argument type mismatch: the argument does not match the parameter type. Convert or validate the value before the call.',
  TS2532: 'Object is possibly undefined: narrow with a check, optional chaining, or a default before using it.',
  TS18048: 'Value is possibly undefined: narrow with a check, optional chaining, or a default before using it.',
  TS18046: "Value is of type 'unknown' (often `catch (err)`): narrow with `err instanceof Error` before reading properties.",
  TS2554: 'Wrong number of arguments for the function signature.',
  TS2580: "Cannot find a Node.js global such as 'process' or 'require': install @types/node (and add \"node\" to compilerOptions.types if types are restricted).",
  TS2591: "Cannot find a Node.js global such as 'process' or 'Buffer': install @types/node (and add \"node\" to compilerOptions.types if types are restricted).",
  TS2367: 'The comparison can never be true because the two types do not overlap (e.g. number vs string). Convert one side first.',
  TS2741: 'A required property is missing from the object literal.',
  TS2366: 'The function has a return type but not every code path returns a value.',
  TS7006: "Parameter implicitly has an 'any' type (noImplicitAny): add a type annotation.",
  TS1308: "'await' is only allowed in async functions: mark the function async.",
  TS2835: 'Relative imports need explicit file extensions under node16/nodenext module resolution: write ./file.js.',
  TS1484: "A type is imported with a value import while verbatimModuleSyntax is on: use `import type`.",
  P1001: 'Prisma cannot reach the database server: check DATABASE_URL, that the database is running, and network/Docker host names.',
  P2002: 'Prisma unique constraint failed: a row with the same unique field already exists. Handle it (e.g. return 409) or use upsert.',
  P2003: 'Prisma foreign key constraint failed: the referenced record does not exist.',
  P2025: 'Prisma record not found for update/delete (or findUniqueOrThrow): check that the record exists or catch P2025 and return 404.',
  PRISMA_NOT_GENERATED: '@prisma/client was not generated: run `npx prisma generate` after installing or changing schema.prisma (add it to postinstall/build).',
  NEST_UNKNOWN_DEPENDENCIES: "Nest can't inject a constructor argument: the provider is not in the module's providers, not exported by its module, or the class lacks @Injectable(). The `?` marks the missing argument.",
  NEST_CIRCULAR_DEPENDENCY: 'Two modules or providers import each other. Break the cycle (move shared code to a third module) or use forwardRef(() => X) on both sides.',
};

export const knowledgeFor = (code?: string): string | undefined => (code ? ERROR_CODES[code] : undefined);
