import type { CrashScenario } from '../types.js';

const esm = JSON.stringify({ name: 'app', type: 'module', dependencies: {} }, null, 2);
const cjs = JSON.stringify({ name: 'app', dependencies: {} }, null, 2);

export const MORE_CRASHES: CrashScenario[] = [
  {
    id: 'destructure-undefined',
    files: {
      'package.json': esm,
      'src/handler.js': ['function {{fn}}({ id, email }) {', '  return `${id}:${email}`;', '}', '', "console.log({{fn}}({ id: 1, email: 'a@b.c' }));", 'console.log({{fn}}());'].join('\n'),
    },
    run: 'node src/handler.js',
    cause: '`{{fn}}()` is called with no argument, so the parameter is `undefined` and destructuring `{ id, email }` from it throws.',
    fix: 'function {{fn}}({ id, email } = {}) {\n  return `${id}:${email}`;\n}',
    why: 'A default value of `{}` makes destructuring safe when the argument is missing; also check the caller that passes nothing.',
    prevent: 'Give destructured parameters defaults and validate required fields at the API boundary.',
    keywords: ['argument', 'destructur', '= {}'],
    vars: { fn: ['formatUser', 'toKey', 'describe'] },
  },
  {
    id: 'lost-this',
    files: {
      'package.json': esm,
      'src/counter.js': [
        'class {{cls}} {',
        '  constructor() {',
        '    this.count = 0;',
        '  }',
        '  tick() {',
        '    this.count += 1;',
        '  }',
        '}',
        '',
        'const c = new {{cls}}();',
        'const run = c.tick;',
        'run();',
      ].join('\n'),
    },
    run: 'node src/counter.js',
    cause: '`c.tick` is copied into `run` and called without its object, so inside `tick` `this` is `undefined` and `this.count` throws.',
    fix: 'const run = c.tick.bind(c);\nrun();',
    why: '`bind` fixes `this` to the instance; an arrow wrapper `() => c.tick()` works too. The same happens when passing methods to `setTimeout` or event handlers.',
    prevent: 'Define callbacks as arrow-function class fields (`tick = () => { ... }`) when they are passed around.',
    keywords: ['this', 'bind'],
    vars: { cls: ['Counter', 'Meter', 'Ticker'] },
  },
  {
    id: 'missing-await-value',
    files: {
      'package.json': esm,
      'src/profile.js': [
        'async function {{fn}}(id) {',
        "  return { id, name: 'Ada' };",
        '}',
        '',
        'const user = {{fn}}(1);',
        'console.log(user.name.toUpperCase());',
      ].join('\n'),
    },
    run: 'node src/profile.js',
    cause: '`{{fn}}` is async, so `{{fn}}(1)` returns a Promise, not the user. `user.name` is `undefined` on the Promise, and calling `.toUpperCase()` on it throws.',
    fix: 'const user = await {{fn}}(1);\nconsole.log(user.name.toUpperCase());',
    why: '`await` unwraps the Promise to the actual object (top-level await works in ESM; inside functions mark them `async`).',
    prevent: 'Turn on TypeScript or the `require-await`/`no-floating-promises` lint rules to catch un-awaited async calls.',
    keywords: ['Promise', 'await'],
    vars: { fn: ['getUser', 'loadProfile', 'fetchAccount'] },
  },
  {
    id: 'not-iterable',
    files: {
      'package.json': esm,
      'src/sum.js': ['const {{data}} = { a: 1, b: 2 };', '', 'let total = 0;', 'for (const n of {{data}}) total += n;', 'console.log(total);'].join('\n'),
    },
    run: 'node src/sum.js',
    cause: '`{{data}}` is a plain object, and `for...of` only works on iterables (arrays, Maps, Sets, strings).',
    fix: 'for (const n of Object.values({{data}})) total += n;',
    why: '`Object.values()` gives an array of the values that can be iterated.',
    prevent: 'Use `Object.entries`/`Object.values` for objects; check the data shape when it comes from JSON.',
    keywords: ['Object.values', 'iterable'],
    vars: { data: ['totals', 'scores', 'counts'] },
  },
  {
    id: 'reduce-empty',
    files: {
      'package.json': esm,
      'src/stats.js': ['const {{list}} = [];', '', 'const sum = {{list}}.reduce((a, b) => a + b);', 'console.log(sum);'].join('\n'),
    },
    run: 'node src/stats.js',
    cause: '`reduce` is called on an empty array without an initial value, so there is no first element to start from.',
    fix: 'const sum = {{list}}.reduce((a, b) => a + b, 0);',
    why: 'Passing `0` as the initial value makes `reduce` return 0 for an empty array.',
    prevent: 'Always pass an initial value to `reduce`.',
    keywords: ['initial value', 'empty', ', 0)'],
    vars: { list: ['prices', 'durations', 'weights'] },
  },
  {
    id: 'object-keys-null',
    files: {
      'package.json': esm,
      'src/flags.js': ['const config = { features: null };', '', 'for (const key of Object.keys(config.features)) {', '  console.log(key);', '}'].join('\n'),
    },
    run: 'node src/flags.js',
    cause: '`config.features` is `null`, and `Object.keys` cannot convert `null` (or `undefined`) to an object.',
    fix: 'for (const key of Object.keys(config.features ?? {})) {',
    why: 'Falling back to an empty object makes the loop a no-op when the value is missing.',
    prevent: 'Default optional config sections to `{}` when loading config.',
    keywords: ['null', '?? {}'],
  },
  {
    id: 'invalid-date',
    files: {
      'package.json': esm,
      'src/dates.js': ["const input = '{{value}}';", 'const date = new Date(input);', 'console.log(date.toISOString());'].join('\n'),
    },
    run: 'node src/dates.js',
    cause: "`new Date('{{value}}')` cannot parse that string, so it is an Invalid Date, and `toISOString()` throws on invalid dates.",
    fix: "const date = new Date(input);\nif (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${input}`);\nconsole.log(date.toISOString());",
    why: 'Checking `getTime()` for NaN detects invalid dates before using them; use ISO 8601 strings (YYYY-MM-DD) as input.',
    prevent: 'Validate date inputs at the boundary (e.g. `z.coerce.date()` or a date library parser).',
    keywords: ['Invalid', 'getTime', 'parse'],
    vars: { value: ['31/12/2024', 'tomorrow', '2024-13-45'] },
  },
  {
    id: 'bigint-json',
    files: {
      'package.json': esm,
      'src/serialize.js': ['const row = { id: {{n}}n, name: "order" };', 'console.log(JSON.stringify(row));'].join('\n'),
    },
    run: 'node src/serialize.js',
    cause: '`row.id` is a BigInt, and `JSON.stringify` has no JSON representation for BigInt values.',
    fix: "console.log(JSON.stringify(row, (key, value) => (typeof value === 'bigint' ? value.toString() : value)));",
    why: 'The replacer converts BigInts to strings; many database drivers return BIGINT columns as BigInt.',
    prevent: 'Convert BigInt IDs to strings in your API layer.',
    keywords: ['BigInt', 'toString'],
    vars: { n: ['9007199254740993', '123456789012345678', '42'] },
  },
  {
    id: 'invalid-regex',
    files: {
      'package.json': esm,
      'src/search.js': ["const term = '{{term}}';", "const re = new RegExp(term, 'i');", "console.log(re.test('price (USD)'));"].join('\n'),
    },
    run: 'node src/search.js',
    cause: "The search term `{{term}}` contains regex special characters, so `new RegExp(term)` builds an invalid pattern.",
    fix: "const escaped = term.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\nconst re = new RegExp(escaped, 'i');",
    why: 'Escaping special characters makes the user text match literally (and avoids ReDoS from user-supplied patterns).',
    prevent: 'Never build regexes from raw user input; escape it or use `String.prototype.includes`.',
    keywords: ['escap', 'special'],
    vars: { term: ['(USD', 'price[', 'a+(b'] },
  },
  {
    id: 'not-a-function-string',
    files: {
      'package.json': esm,
      'src/ids.js': ['function normalize(id) {', '  return id.trim().toLowerCase();', '}', '', "console.log(normalize(' AB12 '));", 'console.log(normalize({{num}}));'].join('\n'),
    },
    run: 'node src/ids.js',
    cause: '`normalize({{num}})` passes a number, and numbers have no `.trim()` method, so `id.trim` is undefined.',
    fix: 'function normalize(id) {\n  return String(id).trim().toLowerCase();\n}',
    why: '`String(id)` accepts numbers and strings alike.',
    prevent: 'Validate or coerce input types at the boundary (query params and JSON numbers vs strings).',
    keywords: ['number', 'String('],
    vars: { num: ['4021', '17', '9001'] },
  },
  {
    id: 'mkdir-nested',
    files: {
      'package.json': esm,
      'src/out.js': ["import { mkdirSync, writeFileSync } from 'node:fs';", '', "mkdirSync('./{{dir}}/2024/q1');", "writeFileSync('./{{dir}}/2024/q1/report.txt', 'ok');"].join('\n'),
    },
    run: 'node src/out.js',
    cause: '`mkdirSync` creates only the last directory; the parent `./{{dir}}/2024` does not exist, so it fails with ENOENT.',
    fix: "mkdirSync('./{{dir}}/2024/q1', { recursive: true });",
    why: '`recursive: true` creates missing parents and does not fail if the directory already exists.',
    prevent: 'Always use `{ recursive: true }` for output directories.',
    keywords: ['recursive', 'parent'],
    vars: { dir: ['reports', 'exports', 'dist'] },
  },
  {
    id: 'eisdir',
    files: {
      'package.json': esm,
      'src/read.js': ["import { readFileSync } from 'node:fs';", '', "const text = readFileSync('./{{dir}}', 'utf8');", 'console.log(text.length);'].join('\n'),
      '{{dir}}/a.txt': 'hello',
    },
    run: 'node src/read.js',
    cause: '`./{{dir}}` is a directory, not a file, so `readFileSync` fails with EISDIR.',
    fix: "import { readdirSync, readFileSync } from 'node:fs';\nimport { join } from 'node:path';\n\nfor (const name of readdirSync('./{{dir}}')) {\n  console.log(readFileSync(join('./{{dir}}', name), 'utf8'));\n}",
    why: 'List the directory and read the files inside it (or point the path at a file).',
    prevent: 'Check `statSync(path).isDirectory()` when a path can be either.',
    keywords: ['directory', 'readdir'],
    vars: { dir: ['data', 'logs', 'fixtures'] },
  },
  {
    id: 'named-export-missing',
    files: {
      'package.json': esm,
      'src/utils.js': 'export function {{real}}(s) {\n  return s.trim();\n}',
      'src/index.js': ["import { {{wrong}} } from './utils.js';", '', "console.log({{wrong}}(' x '));"].join('\n'),
    },
    run: 'node src/index.js',
    cause: "`./utils.js` exports `{{real}}`, not `{{wrong}}`, so the named import does not exist.",
    fix: "import { {{real}} } from './utils.js';",
    why: 'Named imports must match the exported names exactly (case-sensitive).',
    prevent: 'Use editor auto-imports, and grep for the export name when renaming.',
    keywords: ['{{real}}', 'export'],
    vars: { real: ['cleanText', 'slugify', 'formatName'], wrong: ['cleanTxt', 'slugifyText', 'formatname'] },
  },
  {
    id: 'default-export-missing',
    files: {
      'package.json': esm,
      'src/router.js': 'export const {{name}} = { get: () => "ok" };',
      'src/index.js': ["import {{name}} from './router.js';", '', 'console.log({{name}}.get());'].join('\n'),
    },
    run: 'node src/index.js',
    cause: "`./router.js` has only a named export `{{name}}` and no default export, but it is imported as a default.",
    fix: "import { {{name}} } from './router.js';",
    why: 'Use braces for named exports; or add `export default {{name}}` in router.js.',
    prevent: 'Pick one export style per module (prefer named exports) and stay consistent.',
    keywords: ['default', 'named'],
    vars: { name: ['router', 'api', 'routes'] },
  },
  {
    id: 'top-level-await-cjs',
    files: {
      'package.json': cjs,
      'src/main.js': ["const { setTimeout: sleep } = require('node:timers/promises');", '', 'await sleep({{ms}});', "console.log('ready');"].join('\n'),
    },
    run: 'node src/main.js',
    cause: 'Top-level `await` only works in ES modules. This file is CommonJS (no `"type": "module"`), so `await` outside a function is a syntax error.',
    fix: "async function main() {\n  await sleep({{ms}});\n  console.log('ready');\n}\n\nmain().catch((err) => {\n  console.error(err);\n  process.exit(1);\n});",
    why: 'Wrapping the code in an async `main()` works in CommonJS; alternatively switch the package to ESM.',
    prevent: 'Use ESM for new projects so top-level await is available.',
    keywords: ['CommonJS', 'async', 'module'],
    vars: { ms: ['100', '500', '1000'] },
  },
  {
    id: 'promise-all-reject',
    files: {
      'package.json': esm,
      'src/batch.js': [
        'async function {{fn}}(id) {',
        "  if (id === 3) throw new Error(`{{fn}} failed for ${id}`);",
        '  return id;',
        '}',
        '',
        'const results = await Promise.all([1, 2, 3, 4].map({{fn}}));',
        'console.log(results);',
      ].join('\n'),
    },
    run: 'node src/batch.js',
    cause: '`Promise.all` rejects as soon as one task fails: `{{fn}}(3)` throws, so the whole batch rejects and nothing handles it.',
    fix: "const results = await Promise.allSettled([1, 2, 3, 4].map({{fn}}));\nconst failed = results.filter((r) => r.status === 'rejected');\nif (failed.length) console.error(`${failed.length} failed`, failed.map((f) => f.reason.message));",
    why: '`allSettled` waits for every task and reports successes and failures separately; or wrap `Promise.all` in try/catch if one failure should abort.',
    prevent: 'Decide explicitly whether a batch is all-or-nothing (`all` + catch) or best-effort (`allSettled`).',
    keywords: ['allSettled', 'reject'],
    vars: { fn: ['resize', 'upload', 'charge'] },
  },
  {
    id: 'unknown-encoding',
    files: {
      'package.json': esm,
      'src/encode.js': ["const data = Buffer.from('hello', '{{enc}}');", 'console.log(data);'].join('\n'),
    },
    run: 'node src/encode.js',
    cause: "`'{{enc}}'` is not an encoding Node supports, so `Buffer.from` rejects it.",
    fix: "const data = Buffer.from('hello', 'utf8');",
    why: "Supported encodings include 'utf8', 'base64', 'base64url', 'hex', 'latin1' and 'ascii'.",
    prevent: 'Use `Buffer.isEncoding(name)` to validate encodings that come from config or input.',
    keywords: ['utf8', 'encoding'],
    vars: { enc: ['utf-9', 'base-64', 'UTF16'] },
  },
];
