import type { CrashScenario } from '../types.js';

const tsconfig = (extra: Record<string, unknown> = {}) =>
  JSON.stringify({ compilerOptions: { strict: true, target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext', noEmit: true, ...extra }, include: ['src'] }, null, 2);
const pkg = JSON.stringify({ name: 'api', type: 'module', devDependencies: { typescript: '^5.6.0' } }, null, 2);
const ts = (files: Record<string, string>, extra?: Record<string, unknown>) => ({ 'package.json': pkg, 'tsconfig.json': tsconfig(extra), ...files });

export const TS_CRASHES: CrashScenario[] = [
  {
    id: 'ts-possibly-undefined',
    files: ts({ 'src/{{file}}.ts': ['interface {{T}} {', '  id: number;', '  email?: string;', '}', '', 'export function domain(x: {{T}}): string {', "  return x.email.split('@')[1];", '}'].join('\n') }),
    run: '{{tsc}}',
    cause: '`email` is optional (`email?: string`), so `x.email` has type `string | undefined` and calling `.split` on it is not allowed under `strict`.',
    fix: "export function domain(x: {{T}}): string {\n  if (!x.email) return '';\n  return x.email.split('@')[1];\n}",
    why: 'The check narrows `x.email` to `string`; `x.email?.split(...)` works too if returning `undefined` is acceptable.',
    prevent: 'Model optional fields honestly and handle the missing case where the value is used.',
    keywords: ['optional', 'undefined', 'narrow'],
    vars: { file: ['users', 'accounts', 'contacts'], T: ['User', 'Account', 'Contact'] },
  },
  {
    id: 'ts-arg-type',
    files: ts({
      'src/{{file}}.ts': [
        'function findOrder(id: number) {',
        '  return { id };',
        '}',
        '',
        'export function handle(query: Record<string, string>) {',
        '  return findOrder(query.{{param}});',
        '}',
      ].join('\n'),
    }),
    run: '{{tsc}}',
    cause: '`query.{{param}}` is a `string` (query parameters are always strings), but `findOrder` expects a `number`.',
    fix: 'export function handle(query: Record<string, string>) {\n  const id = Number(query.{{param}});\n  if (!Number.isInteger(id)) throw new Error(`Invalid id: ${query.{{param}}}`);\n  return findOrder(id);\n}',
    why: 'Convert and validate the string before passing it on.',
    prevent: 'Parse request input once at the boundary (zod, class-validator, or a ParseIntPipe in NestJS).',
    keywords: ['string', 'number', 'Number('],
    vars: { file: ['orders', 'routes', 'handler'], param: ['id', 'orderId', 'ref'] },
  },
  {
    id: 'ts-unknown-catch',
    files: ts({
      'src/{{file}}.ts': [
        'export async function run(task: () => Promise<void>) {',
        '  try {',
        '    await task();',
        '  } catch (err) {',
        '    console.error(err.message);',
        '  }',
        '}',
      ].join('\n'),
    }),
    run: '{{tsc}}',
    cause: "With `strict`, a `catch` variable has type `unknown` because anything can be thrown, so `err.message` is not allowed until it is narrowed.",
    fix: 'catch (err) {\n  const message = err instanceof Error ? err.message : String(err);\n  console.error(message);\n}',
    why: '`instanceof Error` narrows `err` so `.message` is type-safe, and non-Error values are still logged.',
    prevent: 'Use a small `toError(err: unknown): Error` helper for all catch blocks.',
    keywords: ['unknown', 'instanceof Error'],
    vars: { file: ['jobs', 'runner', 'tasks'] },
  },
  {
    id: 'ts-property-missing',
    files: ts({ 'src/{{file}}.ts': ['type Order = { id: string; total: number };', '', 'export function label(order: Order) {', '  return `${order.id}: ${order.{{wrong}}}`;', '}'].join('\n') }),
    run: '{{tsc}}',
    cause: "`Order` has no `{{wrong}}` property; the amount is called `total`.",
    fix: 'return `${order.id}: ${order.total}`;',
    why: 'Use the property that exists on the type (or add `{{wrong}}` to the type if the data really has it).',
    prevent: 'Let editor autocompletion pick property names, and keep API types generated from the real schema.',
    keywords: ['total', '{{wrong}}'],
    vars: { file: ['orders', 'labels', 'receipt'], wrong: ['amount', 'price', 'sum'] },
  },
  {
    id: 'ts-assign-union',
    files: ts({
      'src/config.ts': ['declare function readEnv(name: string): string | undefined;', '', "export const {{key}}: number = readEnv('{{ENV}}');"].join('\n'),
    }),
    run: '{{tsc}}',
    cause: "`readEnv` returns `string | undefined`, which cannot be assigned to a `number`: the value may be missing, and even when present it is a string.",
    fix: "const raw = readEnv('{{ENV}}');\nexport const {{key}} = raw ? Number(raw) : {{def}};",
    why: 'Handle the missing case with a default and convert the string to a number.',
    prevent: 'Validate all environment variables once at startup (e.g. with zod) and export typed config.',
    keywords: ['string | undefined', 'Number('],
    vars: { key: ['port', 'timeoutMs', 'poolSize'], ENV: ['PORT', 'TIMEOUT_MS', 'POOL_SIZE'], def: ['3000', '5000', '10'] },
  },
  {
    id: 'ts-module-not-found',
    files: ts({ 'src/{{real}}.ts': 'export const settings = { debug: false };', 'src/index.ts': ["import { settings } from './{{typo}}.js';", '', 'export default settings;'].join('\n') }),
    run: '{{tsc}}',
    cause: "`./{{typo}}.js` does not match any file; the module is `src/{{real}}.ts`.",
    fix: "import { settings } from './{{real}}.js';",
    why: 'Under NodeNext the import uses the emitted `.js` name, but the base name must match the real `.ts` file.',
    prevent: 'Use editor auto-imports so paths are always correct.',
    keywords: ['{{real}}', 'path'],
    vars: { real: ['settings', 'config', 'options'], typo: ['setting', 'conf', 'option'] },
  },
  {
    id: 'ts-relative-extension',
    files: ts({ 'src/{{name}}.ts': 'export const add = (a: number, b: number) => a + b;', 'src/index.ts': ["import { add } from './{{name}}';", '', 'export const three = add(1, 2);'].join('\n') }),
    run: '{{tsc}}',
    cause: "With `moduleResolution: NodeNext`, relative ESM imports must include the file extension, as Node itself requires at runtime.",
    fix: "import { add } from './{{name}}.js';",
    why: 'Write the `.js` extension (the name of the compiled file) even though the source is `.ts`.',
    prevent: 'Enable your editor\'s "import module specifier ending: js" setting for NodeNext projects.',
    keywords: ['.js', 'extension', 'NodeNext'],
    vars: { name: ['math', 'utils', 'helpers'] },
  },
  {
    id: 'ts-arg-count',
    files: ts({ 'src/{{file}}.ts': ['function sendMail(to: string, subject: string, body: string) {', '  return { to, subject, body };', '}', '', "export const mail = sendMail('{{to}}', 'Welcome');"].join('\n') }),
    run: '{{tsc}}',
    cause: '`sendMail` takes three arguments (`to`, `subject`, `body`) but is called with two; `body` is missing.',
    fix: "export const mail = sendMail('{{to}}', 'Welcome', 'Thanks for signing up!');",
    why: 'Pass the missing argument, or make it optional (`body = \'\'`) if a default makes sense.',
    prevent: 'For functions with several parameters, take one options object so calls are self-describing.',
    keywords: ['body', 'argument'],
    vars: { file: ['mail', 'notify', 'welcome'], to: ['ada@example.com', 'sam@example.com', 'lee@example.com'] },
  },
  {
    id: 'ts-missing-property-literal',
    files: ts({ 'src/{{file}}.ts': ['interface {{T}} {', '  id: string;', '  name: string;', '  createdAt: Date;', '}', '', "export const sample: {{T}} = { id: '1', name: 'demo' };"].join('\n') }),
    run: '{{tsc}}',
    cause: "The object literal is typed as `{{T}}` but is missing the required `createdAt` property.",
    fix: "export const sample: {{T}} = { id: '1', name: 'demo', createdAt: new Date() };",
    why: 'Provide every required property, or mark it optional in the interface if it really can be missing.',
    prevent: 'Build objects with factory functions that fill defaults.',
    keywords: ['createdAt', 'required'],
    vars: { file: ['projects', 'teams', 'events'], T: ['Project', 'Team', 'Event'] },
  },
  {
    id: 'ts-missing-return',
    files: ts({
      'src/{{file}}.ts': [
        "export function statusText(code: number): string {",
        "  if (code === 200) return 'OK';",
        "  if (code === 404) return 'Not Found';",
        '}',
      ].join('\n'),
    }),
    run: '{{tsc}}',
    cause: 'The function promises to return a `string`, but for any code other than 200 or 404 it falls off the end and returns `undefined`.',
    fix: "export function statusText(code: number): string {\n  if (code === 200) return 'OK';\n  if (code === 404) return 'Not Found';\n  return 'Unknown';\n}",
    why: 'Every code path must return a value of the declared type.',
    prevent: 'Use a lookup object with a default, or a `switch` with an exhaustive `default` branch.',
    keywords: ['return', 'path'],
    vars: { file: ['http', 'status', 'codes'] },
  },
  {
    id: 'ts-implicit-any',
    files: ts({ 'src/{{file}}.ts': ['export function {{fn}}(items, rate) {', '  return items.map((i) => i * rate);', '}'].join('\n') }),
    run: '{{tsc}}',
    cause: '`items` and `rate` have no type annotations, so they are implicitly `any`, which `strict` (noImplicitAny) forbids.',
    fix: 'export function {{fn}}(items: number[], rate: number): number[] {\n  return items.map((i) => i * rate);\n}',
    why: 'Annotating the parameters gives TypeScript what it needs to check the body and the callers.',
    prevent: 'Type public function parameters explicitly; let inference handle local variables.',
    keywords: ['number[]', 'any'],
    vars: { fn: ['applyRate', 'scale', 'withTax'], file: ['pricing', 'math', 'tax'] },
  },
  {
    id: 'ts-await-non-async',
    files: ts({ 'src/{{file}}.ts': ['declare function fetchUser(id: string): Promise<{ name: string }>;', '', 'export function greet(id: string) {', '  const user = await fetchUser(id);', '  return `hi ${user.name}`;', '}'].join('\n') }),
    run: '{{tsc}}',
    cause: '`await` is used inside `greet`, which is not declared `async`.',
    fix: 'export async function greet(id: string) {\n  const user = await fetchUser(id);\n  return `hi ${user.name}`;\n}',
    why: 'Marking the function `async` allows `await`; it now returns `Promise<string>`, so callers must await it.',
    prevent: 'When adding `await` to a function, update its signature and callers together.',
    keywords: ['async'],
    vars: { file: ['greet', 'welcome', 'hello'] },
  },
  {
    id: 'ts-node-types-missing',
    files: ts({ 'src/{{file}}.ts': ["const port = Number(process.env.PORT ?? 3000);", '', 'export default port;'].join('\n') }),
    run: '{{tsc}}',
    cause: "`process` is a Node.js global, and its type definitions come from `@types/node`, which is not installed.",
    fix: 'npm install --save-dev @types/node',
    why: 'With `@types/node` installed (and `"types": ["node"]` if you restrict types in tsconfig), Node globals like `process` and `Buffer` are typed.',
    prevent: 'Add `@types/node` matching your Node major version to every Node TypeScript project.',
    keywords: ['@types/node'],
    vars: { file: ['config', 'server', 'env'] },
  },
  {
    id: 'ts-no-overlap',
    files: ts({ 'src/{{file}}.ts': ['interface Item {', '  id: number;', '}', '', 'export function byId(items: Item[], id: string) {', '  return items.find((i) => i.id === id);', '}'].join('\n') }),
    run: '{{tsc}}',
    cause: '`i.id` is a `number` and `id` is a `string`, so `===` can never be true; TypeScript flags the comparison as a bug.',
    fix: 'export function byId(items: Item[], id: string) {\n  return items.find((i) => i.id === Number(id));\n}',
    why: 'Convert to the same type before comparing (or change the parameter to `id: number`).',
    prevent: 'Convert IDs from URLs or JSON once, at the boundary, to their real type.',
    keywords: ['number', 'string', 'Number('],
    vars: { file: ['items', 'lookup', 'store'] },
  },
  {
    id: 'ts-verbatim-type-import',
    files: ts(
      { 'src/types.ts': 'export interface {{T}} {\n  id: string;\n}', 'src/{{file}}.ts': ["import { {{T}} } from './types.js';", '', 'export const empty: {{T}}[] = [];'].join('\n') },
      { verbatimModuleSyntax: true },
    ),
    run: '{{tsc}}',
    cause: "`{{T}}` is only a type, and with `verbatimModuleSyntax` enabled, type-only imports must say so, because a plain import is kept in the emitted JavaScript.",
    fix: "import type { {{T}} } from './types.js';",
    why: '`import type` is erased at compile time, so no runtime import of a non-existent value remains.',
    prevent: 'Enable the ESLint `consistent-type-imports` rule to add `type` automatically.',
    keywords: ['import type'],
    vars: { T: ['User', 'Order', 'Session'], file: ['store', 'cache', 'repo'] },
  },
];

const nestStack = (root: string) =>
  [
    `    at Injector.lookupComponentInParentModules (${root}/node_modules/@nestjs/core/injector/injector.js:262:19)`,
    `    at Injector.resolveComponentInstance (${root}/node_modules/@nestjs/core/injector/injector.js:215:33)`,
    `    at resolveParam (${root}/node_modules/@nestjs/core/injector/injector.js:129:38)`,
  ].join('\n');

export const NEST_PRISMA_CRASHES: CrashScenario[] = [
  {
    id: 'nest-missing-provider',
    files: {},
    stderr: [
      '[Nest] 4120  - 10/01/2026, 10:12:03 AM   ERROR [ExceptionHandler] Nest can\'t resolve dependencies of the {{Svc}} (?). Please make sure that the argument {{Dep}} at index [0] is available in the {{Mod}} context.',
      '',
      'Potential solutions:',
      '- Is {{Mod}} a valid NestJS module?',
      '- If {{Dep}} is a provider, is it part of the current {{Mod}}?',
      '- If {{Dep}} is exported from a separate @Module, is that module imported within {{Mod}}?',
      '  @Module({',
      '    imports: [ /* the Module containing {{Dep}} */ ]',
      '  })',
      '',
      `Error: Nest can't resolve dependencies of the {{Svc}} (?). Please make sure that the argument {{Dep}} at index [0] is available in the {{Mod}} context.`,
      nestStack('{{root}}'),
    ].join('\n'),
    cause: '`{{Svc}}` injects `{{Dep}}` in its constructor (argument 0, shown as `?`), but `{{Dep}}` is not a provider in `{{Mod}}` and no imported module exports it.',
    fix: "@Module({\n  imports: [{{DepMod}}],\n  providers: [{{Svc}}],\n})\nexport class {{Mod}} {}\n\n// and in {{DepMod}}:\n@Module({ providers: [{{Dep}}], exports: [{{Dep}}] })\nexport class {{DepMod}} {}",
    why: 'A provider is injectable in a module only if it is listed in that module\'s `providers` or exported by a module in its `imports`.',
    prevent: 'Give shared services (Prisma, config, mail) their own module that exports them, and import that module where needed.',
    keywords: ['{{Dep}}', 'providers', 'exports'],
    vars: { Svc: ['UsersService', 'OrdersService', 'AuthService'], Dep: ['PrismaService', 'MailService', 'JwtService'], Mod: ['UsersModule', 'OrdersModule', 'AuthModule'], DepMod: ['PrismaModule', 'MailModule', 'JwtModule'] },
  },
  {
    id: 'nest-interface-injection',
    files: {},
    stderr: [
      "[Nest] 977  - 10/01/2026, 9:41:10 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the {{Svc}} (?). Please make sure that the argument Object at index [0] is available in the {{Mod}} context.",
      '',
      "Error: Nest can't resolve dependencies of the {{Svc}} (?). Please make sure that the argument Object at index [0] is available in the {{Mod}} context.",
      nestStack('{{root}}'),
    ].join('\n'),
    cause: 'The missing argument is reported as `Object`, which means the constructor parameter is typed with an interface or a type-only import. Types disappear at runtime, so Nest has no token to inject.',
    fix: "export const {{TOKEN}} = Symbol('{{TOKEN}}');\n\n@Injectable()\nexport class {{Svc}} {\n  constructor(@Inject({{TOKEN}}) private readonly store: {{Iface}}) {}\n}\n\n// module: providers: [{ provide: {{TOKEN}}, useClass: {{Impl}} }]",
    why: 'Injecting by an explicit token (or by a concrete class instead of an interface) gives Nest something that exists at runtime.',
    prevent: "Don't use `import type` for injected classes, and use `@Inject(TOKEN)` for interfaces.",
    keywords: ['interface', '@Inject', 'token'],
    vars: { Svc: ['ReportsService', 'BillingService', 'SearchService'], Mod: ['ReportsModule', 'BillingModule', 'SearchModule'], TOKEN: ['REPORT_STORE', 'PAYMENT_GATEWAY', 'SEARCH_INDEX'], Iface: ['ReportStore', 'PaymentGateway', 'SearchIndex'], Impl: ['S3ReportStore', 'StripeGateway', 'MeiliSearchIndex'] },
  },
  {
    id: 'nest-circular-module',
    files: {},
    stderr: [
      '[Nest] 5532  - 10/01/2026, 2:03:44 PM   ERROR [ExceptionHandler] Nest cannot create the {{A}} instance.',
      'The module at index [1] of the {{A}} "imports" array is undefined.',
      '',
      'Potential causes:',
      '- A circular dependency between modules. Use forwardRef() to avoid it.',
      '- The module at index [1] is of type "undefined". Check your import statements and the type of the module.',
      '',
      'Scope [AppModule -> {{B}}]',
      'Error: Nest cannot create the {{A}} instance.',
      nestStack('{{root}}'),
    ].join('\n'),
    cause: '`{{A}}` and `{{B}}` import each other. Because of the import cycle, `{{B}}` is still `undefined` when `{{A}}`\'s `imports` array is evaluated.',
    fix: '@Module({\n  imports: [forwardRef(() => {{B}})],\n})\nexport class {{A}} {}\n\n// and in {{B}}: imports: [forwardRef(() => {{A}})]',
    why: '`forwardRef` defers resolving the module until both are defined. The cleaner fix is moving the shared provider into a third module both can import.',
    prevent: 'Keep module dependencies one-directional; extract shared logic instead of importing each other.',
    keywords: ['circular', 'forwardRef'],
    vars: { A: ['UsersModule', 'OrdersModule', 'AuthModule'], B: ['AuthModule', 'PaymentsModule', 'UsersModule'] },
  },
  {
    id: 'prisma-not-generated',
    files: {},
    stderr: [
      '{{root}}/node_modules/.prisma/client/default.js:43',
      '    throw new Error(\'@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.\');',
      '    ^',
      '',
      'Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.',
      '    at new PrismaClient ({{root}}/node_modules/.prisma/client/default.js:43:11)',
      '    at Object.<anonymous> ({{root}}/dist/{{file}}.js:4:16)',
      '',
      'Node.js v20.18.1',
    ].join('\n'),
    cause: 'The Prisma client code is generated from `schema.prisma`, and it has not been generated in this install (fresh clone, CI, Docker image, or after a schema change).',
    fix: 'npx prisma generate',
    why: 'Generating creates the typed client; add `"postinstall": "prisma generate"` to package.json (and run it in your Dockerfile) so every install does it.',
    prevent: 'Run `prisma generate` in postinstall/build steps and after every schema change.',
    keywords: ['prisma generate', 'postinstall'],
    vars: { file: ['main', 'db', 'server'] },
  },
  {
    id: 'prisma-unique-p2002',
    files: {},
    stderr: [
      'PrismaClientKnownRequestError: ',
      'Invalid `prisma.{{model}}.create()` invocation in',
      '{{root}}/src/{{model}}s/{{model}}s.service.ts:18:42',
      '',
      '  15   async create(dto: Create{{Model}}Dto) {',
      '  16     return this.prisma.{{model}}.create({ data: dto });',
      '→ 18 ',
      'Unique constraint failed on the fields: (`{{field}}`)',
      '    at Ln.handleRequestError ({{root}}/node_modules/@prisma/client/runtime/library.js:121:7753)',
      '    at async {{Model}}sService.create ({{root}}/src/{{model}}s/{{model}}s.service.ts:18:20) {',
      "  code: 'P2002',",
      "  clientVersion: '5.22.0',",
      "  meta: { modelName: '{{Model}}', target: [ '{{field}}' ] }",
      '}',
    ].join('\n'),
    cause: 'A `{{model}}` with the same `{{field}}` already exists, and `{{field}}` has a unique constraint, so the insert is rejected (P2002). Unhandled, this becomes a 500.',
    fix: "import { Prisma } from '@prisma/client';\n\ntry {\n  return await this.prisma.{{model}}.create({ data: dto });\n} catch (e) {\n  if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') {\n    throw new ConflictException('{{field}} already in use');\n  }\n  throw e;\n}",
    why: 'Map the known Prisma error to a 409 response; let the database constraint, not a prior lookup, enforce uniqueness.',
    prevent: 'Add a global exception filter that maps P2002 → 409 and P2025 → 404.',
    keywords: ['P2002', 'unique', '409'],
    vars: { model: ['user', 'tag', 'team'], Model: ['User', 'Tag', 'Team'], field: ['email', 'slug', 'name'] },
  },
  {
    id: 'prisma-not-found-p2025',
    files: {},
    stderr: [
      'PrismaClientKnownRequestError: ',
      'Invalid `prisma.{{model}}.update()` invocation in',
      '{{root}}/src/{{model}}s/{{model}}s.service.ts:31:38',
      '',
      'An operation failed because it depends on one or more records that were required but not found. Record to update not found.',
      '    at Ln.handleRequestError ({{root}}/node_modules/@prisma/client/runtime/library.js:121:7753)',
      '    at async {{Model}}sService.update ({{root}}/src/{{model}}s/{{model}}s.service.ts:31:12) {',
      "  code: 'P2025',",
      "  clientVersion: '5.22.0',",
      "  meta: { modelName: '{{Model}}', cause: 'Record to update not found.' }",
      '}',
    ].join('\n'),
    cause: '`prisma.{{model}}.update()` was called with a `where` that matches no row (the id does not exist or was deleted), so Prisma throws P2025.',
    fix: "try {\n  return await this.prisma.{{model}}.update({ where: { id }, data: dto });\n} catch (e) {\n  if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2025') {\n    throw new NotFoundException(`{{Model}} ${id} not found`);\n  }\n  throw e;\n}",
    why: 'Turn the missing-record error into a 404 instead of a 500.',
    prevent: 'Handle P2025 centrally in an exception filter; use `updateMany` when "no match" is not an error.',
    keywords: ['P2025', 'not found', '404'],
    vars: { model: ['post', 'invoice', 'project'], Model: ['Post', 'Invoice', 'Project'] },
  },
  {
    id: 'prisma-cannot-reach-p1001',
    files: {},
    stderr: [
      'PrismaClientInitializationError: ',
      'Invalid `prisma.{{model}}.findMany()` invocation:',
      '',
      "Can't reach database server at `localhost:{{port}}`",
      '',
      'Please make sure your database server is running at `localhost:{{port}}`.',
      '    at $n.handleRequestError ({{root}}/node_modules/@prisma/client/runtime/library.js:121:7615)',
      "  errorCode: 'P1001',",
      "  clientVersion: '5.22.0'",
    ].join('\n'),
    cause: 'Prisma cannot open a connection to the database at `localhost:{{port}}` from `DATABASE_URL`. The database is not running, or (very often in Docker) `localhost` points at the app container instead of the database container.',
    fix: 'DATABASE_URL="{{scheme}}://user:pass@db:{{port}}/app"',
    why: 'Inside Docker Compose use the service name (e.g. `db`) as the host; outside Docker, start the database or fix the host/port.',
    prevent: 'Add a healthcheck plus `depends_on: condition: service_healthy` so the app starts after the database.',
    keywords: ['DATABASE_URL', 'running', 'Docker'],
    vars: { model: ['user', 'order', 'product'], port: ['5432', '3306', '5432'], scheme: ['postgresql', 'mysql', 'postgresql'] },
  },
];
