import type { CrashScenario } from '../types.js';

const esm = JSON.stringify({ name: 'app', type: 'module', dependencies: {} }, null, 2);
const cjs = JSON.stringify({ name: 'app', dependencies: {} }, null, 2);

export const CRASHES: CrashScenario[] = [
  {
    id: 'nested-undefined',
    files: {
      'package.json': esm,
      'src/{{file}}.js': [
        "const {{list}} = [{ id: 1, profile: { name: 'Ada' } }, { id: 2 }];",
        '',
        'export function displayName(id) {',
        '  const {{item}} = {{list}}.find((u) => u.id === id);',
        '  return {{item}}.profile.name.toUpperCase();',
        '}',
        '',
        'console.log(displayName(1));',
        'console.log(displayName(2));',
      ].join('\n'),
    },
    run: 'node src/{{file}}.js',
    cause: '`{{item}}` is found for id 2, but that record has no `profile`, so `{{item}}.profile` is `undefined` and reading `.name` on it throws.',
    fix: "return {{item}}?.profile?.name?.toUpperCase() ?? 'Unknown';",
    why: 'Optional chaining stops at the first missing value and `??` supplies a fallback instead of crashing.',
    prevent: 'Validate records at the boundary (or type them) so optional fields are handled explicitly.',
    keywords: ['profile', 'undefined', '?.'],
    vars: { file: ['users', 'accounts', 'members'], list: ['users', 'accounts', 'members'], item: ['user', 'account', 'member'] },
  },
  {
    id: 'find-returns-undefined',
    files: {
      'package.json': esm,
      'src/cart.js': [
        "const {{items}} = [{ sku: 'A1', price: 10 }, { sku: 'B2', price: 25 }];",
        '',
        'function priceOf(sku) {',
        '  const found = {{items}}.find((p) => p.sku === sku);',
        '  return found.price;',
        '}',
        '',
        "console.log(priceOf('A1') + priceOf('{{missing}}'));",
      ].join('\n'),
    },
    run: 'node src/cart.js',
    cause: "`Array.prototype.find` returns `undefined` when nothing matches; no item has sku '{{missing}}', so `found.price` reads a property of `undefined`.",
    fix: 'const found = {{items}}.find((p) => p.sku === sku);\nif (!found) throw new Error(`Unknown sku: ${sku}`);\nreturn found.price;',
    why: 'Checking the result of `find` turns a vague TypeError into a clear, handled error.',
    prevent: 'Always handle the not-found case of `find`, `get` and database lookups.',
    keywords: ['find', 'undefined', 'sku'],
    vars: { items: ['products', 'catalog', 'items'], missing: ['C3', 'Z9', 'X0'] },
  },
  {
    id: 'map-not-function',
    files: {
      'package.json': esm,
      'src/report.js': [
        'const response = { data: { {{key}}: [{ id: 1 }, { id: 2 }] } };',
        '',
        'const ids = response.data.map((row) => row.id);',
        'console.log(ids);',
      ].join('\n'),
    },
    run: 'node src/report.js',
    cause: '`response.data` is an object (`{ {{key}}: [...] }`), not an array, so it has no `.map` method.',
    fix: 'const ids = response.data.{{key}}.map((row) => row.id);',
    why: 'The array lives under `data.{{key}}`; map over that.',
    prevent: 'Log or type the API response shape before transforming it; use `Array.isArray` guards for untrusted data.',
    keywords: ['array', '{{key}}', 'map'],
    vars: { key: ['items', 'rows', 'results'] },
  },
  {
    id: 'await-outside-async',
    files: {
      'package.json': cjs,
      'src/load.js': [
        "const fs = require('node:fs/promises');",
        '',
        'function loadConfig(path) {',
        "  const text = await fs.readFile(path, 'utf8');",
        '  return JSON.parse(text);',
        '}',
        '',
        'module.exports = { loadConfig };',
      ].join('\n'),
    },
    run: 'node src/load.js',
    cause: '`await` is used inside `loadConfig`, which is a regular function. `await` is only allowed in `async` functions (or ESM top level).',
    fix: "async function loadConfig(path) {\n  const text = await fs.readFile(path, 'utf8');\n  return JSON.parse(text);\n}",
    why: 'Marking the function `async` makes `await` valid; callers must now `await loadConfig(...)`.',
    prevent: 'Enable ESLint (or TypeScript) in your editor so syntax errors like this show before running.',
    keywords: ['async', 'await'],
  },
  {
    id: 'require-in-esm',
    files: {
      'package.json': esm,
      'src/server.js': ["const {{mod}} = require('node:{{mod}}');", '', "console.log({{mod}}.platform ? 'ok' : {{mod}});"].join('\n'),
    },
    run: 'node src/server.js',
    cause: 'package.json has `"type": "module"`, so `.js` files are ES modules where `require` does not exist.',
    fix: "import {{mod}} from 'node:{{mod}}';",
    why: 'ES modules load dependencies with `import`; use `createRequire(import.meta.url)` only if you must load CommonJS-only code.',
    prevent: 'Pick one module system per package and keep `"type"` and file extensions (.mjs/.cjs) consistent.',
    keywords: ['type', 'module', 'import'],
    vars: { mod: ['os', 'process', 'path'] },
  },
  {
    id: 'dirname-in-esm',
    files: {
      'package.json': esm,
      'src/paths.js': ["import { join } from 'node:path';", '', "const file = join(__dirname, '{{asset}}');", 'console.log(file);'].join('\n'),
    },
    run: 'node src/paths.js',
    cause: '`__dirname` only exists in CommonJS. This file is an ES module (`"type": "module"`), so it is not defined.',
    fix: "import { join } from 'node:path';\n\nconst file = join(import.meta.dirname, '{{asset}}');",
    why: '`import.meta.dirname` (Node 20.11+) is the ESM equivalent; on older Node use `fileURLToPath(new URL(\'.\', import.meta.url))`.',
    prevent: 'When converting CJS to ESM, search for `__dirname`, `__filename` and `require` first.',
    keywords: ['import.meta', '__dirname', 'module'],
    vars: { asset: ['templates', 'public', 'config.json'] },
  },
  {
    id: 'esm-missing-extension',
    files: {
      'package.json': esm,
      'src/{{name}}.js': 'export const add = (a, b) => a + b;',
      'src/index.js': ["import { add } from './{{name}}';", '', 'console.log(add(2, 3));'].join('\n'),
    },
    run: 'node src/index.js',
    cause: "ES modules do not guess file extensions, so `./{{name}}` does not resolve to `./{{name}}.js`.",
    fix: "import { add } from './{{name}}.js';",
    why: 'ESM resolution requires the full relative path including the extension.',
    prevent: 'Use full extensions in ESM imports; TypeScript users should write `.js` in import paths too.',
    keywords: ['extension', '.js'],
    vars: { name: ['math', 'utils', 'helpers'] },
  },
  {
    id: 'require-typo',
    files: {
      'package.json': cjs,
      'src/config.js': 'module.exports = { port: 3000 };',
      'src/app.js': ["const config = require('./{{typo}}');", '', 'console.log(config.port);'].join('\n'),
    },
    run: 'node src/app.js',
    cause: "`require('./{{typo}}')` points at a file that does not exist; the module is `./config.js`.",
    fix: "const config = require('./config');",
    why: 'The path must match the real file name (relative to the requiring file).',
    prevent: 'Rely on editor path autocompletion, and keep file names consistent.',
    keywords: ['config', 'path'],
    vars: { typo: ['confg', 'configs', 'conf'] },
  },
  {
    id: 'package-not-installed',
    files: {
      'package.json': esm,
      'src/index.js': ["import {{pkgVar}} from '{{pkg}}';", '', 'console.log(typeof {{pkgVar}});'].join('\n'),
    },
    run: 'node src/index.js',
    cause: "The package `{{pkg}}` is imported but not installed in node_modules (and not listed in package.json).",
    fix: 'npm install {{pkg}}',
    why: 'Installing it adds it to dependencies and node_modules so the import resolves.',
    prevent: 'Run `npm ci` after pulling changes, and keep every imported package declared in package.json.',
    keywords: ['npm install', '{{pkg}}'],
    vars: { pkg: ['dotenv', 'zod', 'express'], pkgVar: ['dotenv', 'z', 'express'] },
  },
  {
    id: 'econnrefused-db',
    files: {
      'package.json': esm,
      'src/db.js': [
        "import net from 'node:net';",
        '',
        "const socket = net.connect({ host: '127.0.0.1', port: {{port}} });",
        "socket.on('connect', () => console.log('connected to {{service}}'));",
      ].join('\n'),
    },
    stderr: [
      'node:events:497',
      "      throw er; // Unhandled 'error' event",
      '      ^',
      '',
      'Error: connect ECONNREFUSED 127.0.0.1:{{port}}',
      '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)',
      "Emitted 'error' event on Socket instance at:",
      '    at emitErrorNT (node:internal/streams/destroy:169:8)',
      '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {',
      '  errno: -111,',
      "  code: 'ECONNREFUSED',",
      "  syscall: 'connect',",
      "  address: '127.0.0.1',",
      '  port: {{port}}',
      '}',
      '',
      'Node.js v20.18.1',
    ].join('\n'),
    cause: 'Nothing is listening on 127.0.0.1:{{port}}, so the {{service}} connection is refused. The server is not running, or it runs on another host/port (for example inside Docker).',
    fix: "socket.on('error', (err) => {\n  console.error('Cannot reach {{service}}:', err.message);\n  process.exitCode = 1;\n});",
    why: 'Start {{service}} (or fix host/port); handling the `error` event turns the crash into a clear message.',
    prevent: 'Read host/port from environment variables and add a startup health check with retries.',
    keywords: ['{{port}}', 'running', 'error'],
    vars: { port: ['5432', '6379', '27017'], service: ['Postgres', 'Redis', 'MongoDB'] },
  },
  {
    id: 'eaddrinuse',
    files: {
      'package.json': esm,
      'src/server.js': [
        "import http from 'node:http';",
        '',
        'const PORT = {{port}};',
        "const handler = (req, res) => res.end('ok');",
        'http.createServer(handler).listen(PORT);',
        'http.createServer(handler).listen(PORT);',
      ].join('\n'),
    },
    run: 'node src/server.js',
    cause: 'Port {{port}} is already in use: the code calls `listen({{port}})` twice (in real projects, often a second instance or a previous dev server still running).',
    fix: "const server = http.createServer(handler);\nserver.listen(process.env.PORT ?? {{port}});\nserver.on('error', (err) => {\n  if (err.code === 'EADDRINUSE') console.error(`Port ${err.port} is busy`);\n});",
    why: 'Only one server can bind a port; listen once and handle the error.',
    prevent: 'Make the port configurable and stop old processes (`npx kill-port {{port}}`).',
    keywords: ['{{port}}', 'already', 'listen'],
    vars: { port: ['3000', '8080', '4000'] },
  },
  {
    id: 'enoent-cwd',
    files: {
      'package.json': esm,
      'src/settings.js': ["import { readFileSync } from 'node:fs';", '', "const settings = JSON.parse(readFileSync('./{{json}}', 'utf8'));", 'console.log(settings);'].join('\n'),
      'src/{{json}}': '{ "debug": true }',
    },
    run: 'node src/settings.js',
    cause: "`./{{json}}` is resolved against the current working directory (the project root), not against `src/` where the file lives.",
    fix: "const settings = JSON.parse(readFileSync(new URL('./{{json}}', import.meta.url), 'utf8'));",
    why: 'Resolving relative to `import.meta.url` makes the path independent of where node is started.',
    prevent: 'Never rely on `process.cwd()` for files that ship with your code.',
    keywords: ['working directory', 'import.meta'],
    vars: { json: ['settings.json', 'defaults.json', 'config.json'] },
  },
  {
    id: 'json-parse-empty',
    files: {
      'package.json': esm,
      'src/parse.js': ["const body = '{{body}}';", '', 'const data = JSON.parse(body);', 'console.log(data);'].join('\n'),
    },
    run: 'node src/parse.js',
    cause: 'The string passed to `JSON.parse` is not valid JSON ({{what}}). This usually means an empty or HTML response was parsed as JSON.',
    fix: "let data;\ntry {\n  data = JSON.parse(body);\n} catch {\n  throw new Error(`Expected JSON, got: ${body.slice(0, 100)}`);\n}",
    why: 'Wrapping the parse shows what was actually received instead of a vague SyntaxError.',
    prevent: 'Check `response.ok` and the `content-type` header before calling `response.json()`.',
    keywords: ['JSON', 'valid'],
    vars: { body: ['', '<html>Not Found</html>', "{name: 'x'}"], what: ['it is empty', 'it is an HTML page', 'keys are unquoted'] },
  },
  {
    id: 'headers-sent',
    files: {
      'package.json': esm,
      'src/api.js': [
        "import http from 'node:http';",
        '',
        'const server = http.createServer((req, res) => {',
        '  if (!req.headers.authorization) {',
        '    res.writeHead(401);',
        "    res.end('unauthorized');",
        '  }',
        "  res.writeHead(200, { 'content-type': 'application/json' });",
        "  res.end('{}');",
        '});',
        '',
        'server.listen(0, () => {',
        '  http.get(`http://127.0.0.1:${server.address().port}`, () => server.close());',
        '});',
      ].join('\n'),
    },
    run: 'node src/api.js',
    cause: 'When the auth header is missing the handler sends a 401 but does not `return`, so execution continues and `res.writeHead(200)` runs after the response was already sent.',
    fix: "  if (!req.headers.authorization) {\n    res.writeHead(401);\n    return res.end('unauthorized');\n  }",
    why: 'Returning after sending guarantees only one response per request.',
    prevent: 'Always `return` when sending a response early (same rule for Express `res.send/json`).',
    keywords: ['return', 'already', '401'],
  },
  {
    id: 'invalid-arg-env',
    files: {
      'package.json': esm,
      'src/boot.js': ["import { readFileSync } from 'node:fs';", '', "const cert = readFileSync(process.env.{{env}}, 'utf8');", 'console.log(cert.length);'].join('\n'),
    },
    run: 'node src/boot.js',
    cause: '`process.env.{{env}}` is not set, so `readFileSync` receives `undefined` instead of a path.',
    fix: "const path = process.env.{{env}};\nif (!path) throw new Error('{{env}} is not set');\nconst cert = readFileSync(path, 'utf8');",
    why: 'Failing fast with the variable name makes the configuration problem obvious.',
    prevent: 'Validate required environment variables at startup (e.g. with zod or envalid) and document them in .env.example.',
    keywords: ['{{env}}', 'undefined', 'environment'],
    vars: { env: ['CERT_PATH', 'TLS_CERT', 'KEY_FILE'] },
  },
  {
    id: 'unhandled-rejection',
    files: {
      'package.json': esm,
      'src/jobs.js': [
        'async function {{fn}}(id) {',
        "  if (!id) throw new Error('{{msg}}');",
        '  return { id };',
        '}',
        '',
        '{{fn}}();',
        "console.log('scheduled');",
      ].join('\n'),
    },
    run: 'node src/jobs.js',
    cause: '`{{fn}}()` is called without an id, so the async function rejects, and the call is neither awaited nor given a `.catch`, which makes it an unhandled rejection that crashes Node.',
    fix: 'try {\n  await {{fn}}(jobId);\n} catch (err) {\n  console.error(\'{{fn}} failed:\', err);\n}',
    why: 'Awaiting inside try/catch (or adding `.catch`) handles the rejection; also pass the required argument.',
    prevent: 'Enable the `@typescript-eslint/no-floating-promises` or `promise/catch-or-return` lint rule.',
    keywords: ['await', 'catch', 'reject'],
    vars: { fn: ['sendEmail', 'syncOrder', 'processJob'], msg: ['recipient required', 'order id required', 'job id required'] },
  },
  {
    id: 'stack-overflow',
    files: {
      'package.json': esm,
      'src/tree.js': [
        'function {{fn}}(node) {',
        '  return 1 + {{fn}}(node.children[0] ?? node);',
        '}',
        '',
        'console.log({{fn}}({ children: [] }));',
      ].join('\n'),
    },
    run: 'node src/tree.js',
    cause: '`{{fn}}` has no base case: when a node has no children it recurses on the same node forever until the call stack overflows.',
    fix: 'function {{fn}}(node) {\n  if (!node.children.length) return 1;\n  return 1 + Math.max(...node.children.map({{fn}}));\n}',
    why: 'Recursion must stop on leaf nodes.',
    prevent: 'Write the base case first, and test recursive functions on the smallest input.',
    keywords: ['base case', 'recurs'],
    vars: { fn: ['depth', 'countNodes', 'walk'] },
  },
  {
    id: 'const-reassign',
    files: {
      'package.json': esm,
      'src/counter.js': ['const {{name}} = 0;', '', 'for (const n of [1, 2, 3]) {', '  {{name}} += n;', '}', 'console.log({{name}});'].join('\n'),
    },
    run: 'node src/counter.js',
    cause: '`{{name}}` is declared with `const`, so `{{name}} += n` tries to reassign a constant.',
    fix: 'let {{name}} = 0;',
    why: '`let` allows reassignment; or compute it with `reduce` and keep `const`.',
    prevent: 'Use `const` by default and switch to `let` only for values that change.',
    keywords: ['const', 'let'],
    vars: { name: ['total', 'sum', 'count'] },
  },
  {
    id: 'tdz',
    files: {
      'package.json': esm,
      'src/app.js': ['console.log(start());', '', 'const {{cfg}} = { port: 3000 };', 'function start() {', '  return `listening on ${{{cfg}}.port}`;', '}'].join('\n'),
    },
    run: 'node src/app.js',
    cause: '`start()` runs on line 1 and reads `{{cfg}}`, but `const {{cfg}}` is only initialized on line 3 (temporal dead zone).',
    fix: 'const {{cfg}} = { port: 3000 };\nfunction start() {\n  return `listening on ${{{cfg}}.port}`;\n}\nconsole.log(start());',
    why: 'Declare values before code that uses them runs.',
    prevent: 'Keep startup code at the bottom of the module; watch for circular imports, which cause the same error.',
    keywords: ['before', 'initializ'],
    vars: { cfg: ['config', 'settings', 'options'] },
  },
  {
    id: 'invalid-url',
    files: {
      'package.json': esm,
      'src/client.js': ["const endpoint = new URL('{{path}}');", 'console.log(endpoint.href);'].join('\n'),
    },
    run: 'node src/client.js',
    cause: "`new URL('{{path}}')` gets a relative path without a base, which is not a valid absolute URL.",
    fix: "const endpoint = new URL('{{path}}', process.env.API_BASE ?? 'http://localhost:3000');",
    why: 'The second argument is the base that relative paths are resolved against.',
    prevent: 'Keep the API base URL in config and build URLs with `new URL(path, base)`.',
    keywords: ['base', 'relative'],
    vars: { path: ['/api/users', '/v1/orders', 'health'] },
  },
  {
    id: 'class-without-new',
    files: {
      'package.json': esm,
      'src/service.js': ['class {{cls}} {', '  constructor(name) {', '    this.name = name;', '  }', '}', '', "const svc = {{cls}}('main');", 'console.log(svc.name);'].join('\n'),
    },
    run: 'node src/service.js',
    cause: '`{{cls}}` is a class, and classes cannot be called like functions.',
    fix: "const svc = new {{cls}}('main');",
    why: 'Class constructors must be invoked with `new`.',
    prevent: 'Name classes in PascalCase and factories in camelCase so the difference is visible.',
    keywords: ['new'],
    vars: { cls: ['Logger', 'Cache', 'Queue'] },
  },
  {
    id: 'circular-json',
    files: {
      'package.json': esm,
      'src/log.js': ["const {{a}} = { name: 'a' };", "const {{b}} = { name: 'b', parent: {{a}} };", '{{a}}.child = {{b}};', '', 'console.log(JSON.stringify({{a}}));'].join('\n'),
    },
    run: 'node src/log.js',
    cause: '`{{a}}.child` points to `{{b}}` and `{{b}}.parent` points back to `{{a}}`, so the object graph is circular and JSON cannot represent it.',
    fix: "console.log(JSON.stringify({{a}}, (key, value) => (key === 'parent' ? undefined : value)));",
    why: 'The replacer drops the back-reference; alternatively use `util.inspect` for logging.',
    prevent: 'Serialize plain DTOs, not live objects such as requests, sockets or ORM entities.',
    keywords: ['circular', 'parent'],
    vars: { a: ['root', 'order', 'team'], b: ['leaf', 'line', 'player'] },
  },
  {
    id: 'unhandled-error-event',
    files: {
      'package.json': esm,
      'src/copy.js': ["import { createReadStream } from 'node:fs';", '', "const input = createReadStream('./{{file}}');", "input.on('data', (chunk) => console.log(chunk.length));"].join('\n'),
    },
    run: 'node src/copy.js',
    cause: "`./{{file}}` does not exist, so the read stream emits an `error` event, and there is no `error` listener, which makes Node throw it.",
    fix: "input.on('error', (err) => {\n  console.error('Cannot read {{file}}:', err.message);\n});",
    why: 'Streams and EventEmitters crash the process on unhandled `error` events; listen for them.',
    prevent: 'Use `stream/promises` `pipeline()`, which forwards errors to a single await/catch.',
    keywords: ['error', 'listener', 'ENOENT'],
    vars: { file: ['input.csv', 'data.log', 'export.json'] },
  },
  {
    id: 'ts-extension',
    files: {
      'package.json': esm,
      'src/index.ts': ["const greet = (name: string): string => `hello ${name}`;", "console.log(greet('dev'));"].join('\n'),
    },
    run: 'node src/index.ts',
    cause: 'Node is asked to run a `.ts` file directly. This Node version does not strip TypeScript types, so it does not know the `.ts` extension.',
    fix: 'npx tsx src/index.ts',
    why: '`tsx` (or compiling with `tsc` first) runs TypeScript; Node 22.6+ can also run it with `--experimental-strip-types`.',
    prevent: 'Add a `dev` script (`tsx watch src/index.ts`) and a `build` step for production.',
    keywords: ['tsx', 'TypeScript'],
  },
  {
    id: 'exports-subpath',
    files: {
      'package.json': esm,
      'node_modules/{{pkg}}/package.json': JSON.stringify({ name: '{{pkg}}', type: 'module', exports: { '.': './index.js' } }),
      'node_modules/{{pkg}}/index.js': 'export const parse = (s) => s.split(",");',
      'node_modules/{{pkg}}/lib/{{sub}}.js': 'export const parse = (s) => s.split(",");',
      'src/index.js': ["import { parse } from '{{pkg}}/lib/{{sub}}.js';", "console.log(parse('a,b'));"].join('\n'),
    },
    run: 'node src/index.js',
    cause: "`{{pkg}}` declares an `exports` map that only exposes `.`, so the deep import `{{pkg}}/lib/{{sub}}.js` is blocked.",
    fix: "import { parse } from '{{pkg}}';",
    why: 'Only paths listed in `exports` are public; import from the package entry point.',
    prevent: 'Avoid deep imports into packages; they break when packages add an exports map.',
    keywords: ['exports', 'entry'],
    vars: { pkg: ['csv-lite', 'tiny-parse', 'fastcsv-x'], sub: ['parser', 'core', 'internal'] },
  },
  {
    id: 'json-import-attribute',
    files: {
      'package.json': esm,
      'src/{{json}}': '{ "version": "1.0.0" }',
      'src/index.js': ["import data from './{{json}}';", 'console.log(data.version);'].join('\n'),
    },
    run: 'node src/index.js',
    cause: 'Importing a JSON file in ESM requires an import attribute declaring its type.',
    fix: "import data from './{{json}}' with { type: 'json' };",
    why: 'The attribute tells Node to parse the file as JSON (older Node versions used `assert { type: \'json\' }`).',
    prevent: "For config, `JSON.parse(readFileSync(new URL('./file.json', import.meta.url)))` works on every Node version.",
    keywords: ["type: 'json'", 'with'],
    vars: { json: ['meta.json', 'version.json', 'data.json'] },
  },
  {
    id: 'import-in-cjs',
    files: {
      'package.json': cjs,
      'src/index.js': ["import express from 'express';", '', 'const app = express();', 'app.listen(3000);'].join('\n'),
    },
    run: 'node src/index.js',
    cause: 'The file uses `import` syntax, but package.json has no `"type": "module"`, so Node treats `.js` files as CommonJS where `import` statements are invalid.',
    fix: '// package.json\n{\n  "type": "module"\n}',
    why: 'With `"type": "module"`, `.js` files are ES modules (or rename the file to `.mjs`; or use `require` instead).',
    prevent: 'Decide on ESM vs CommonJS when creating the project and set `"type"` accordingly.',
    keywords: ['"type": "module"', 'CommonJS'],
  },
  {
    id: 'write-after-end',
    files: {
      'package.json': esm,
      'src/export.js': [
        "import { createWriteStream } from 'node:fs';",
        "import { tmpdir } from 'node:os';",
        "import { join } from 'node:path';",
        '',
        "const out = createWriteStream(join(tmpdir(), '{{file}}'));",
        "out.write('id,name\\n');",
        'out.end();',
        "out.write('1,{{row}}\\n');",
      ].join('\n'),
    },
    run: 'node src/export.js',
    cause: '`out.write()` is called after `out.end()`, and a stream cannot accept data once it has been ended.',
    fix: "out.write('id,name\\n');\nout.write('1,{{row}}\\n');\nout.end();",
    why: 'End the stream only after the last write (or pass the final chunk to `end()`).',
    prevent: 'Use `pipeline()` with a generator so ordering and ending are handled for you.',
    keywords: ['end', 'write'],
    vars: { file: ['users.csv', 'orders.csv', 'report.csv'], row: ['ada', 'order-1', 'q3'] },
  },
  {
    id: 'bigint-mix',
    files: {
      'package.json': esm,
      'src/ids.js': ['const {{id}} = 9007199254740993n;', 'const next = {{id}} + 1;', 'console.log(next);'].join('\n'),
    },
    run: 'node src/ids.js',
    cause: '`{{id}}` is a BigInt and `1` is a Number; JavaScript does not mix the two in arithmetic.',
    fix: 'const next = {{id}} + 1n;',
    why: 'Use BigInt literals (`1n`) or convert explicitly with `BigInt()` / `Number()`.',
    prevent: 'Keep large IDs as strings or BigInt consistently across the codebase.',
    keywords: ['BigInt', '1n'],
    vars: { id: ['userId', 'snowflake', 'orderId'] },
  },
  {
    id: 'require-esm-static',
    files: { 'src/server.js': "const fetch = require('node-fetch');\n\nmodule.exports = async (url) => (await fetch(url)).json();" },
    stderr: [
      '{{root}}/src/server.js:1',
      "const fetch = require('node-fetch');",
      '              ^',
      '',
      'Error [ERR_REQUIRE_ESM]: require() of ES Module {{root}}/node_modules/node-fetch/src/index.js from {{root}}/src/server.js not supported.',
      'Instead change the require of index.js in {{root}}/src/server.js to a dynamic import() which is available in all CommonJS modules.',
      '    at Object.<anonymous> ({{root}}/src/server.js:1:15) {',
      "  code: 'ERR_REQUIRE_ESM'",
      '}',
      '',
      'Node.js v18.19.0',
    ].join('\n'),
    cause: 'node-fetch v3 is ESM-only, and this CommonJS file loads it with `require()`, which Node 18 cannot do for ES modules.',
    fix: "module.exports = async (url) => (await fetch(url)).json();",
    why: 'Node 18+ has a global `fetch`, so the dependency can be removed; otherwise use `await import(\'node-fetch\')` or pin node-fetch@2.',
    prevent: 'Check whether a package is ESM-only before upgrading a major version in a CommonJS project.',
    keywords: ['ESM', 'fetch', 'import('],
  },
  {
    id: 'openssl-legacy-static',
    files: {},
    stderr: [
      'Error: error:0308010C:digital envelope routines::unsupported',
      '    at new Hash (node:internal/crypto/hash:69:19)',
      '    at Object.createHash (node:crypto:133:10)',
      '    at module.exports ({{root}}/node_modules/webpack/lib/util/createHash.js:135:53)',
      '    at NormalModule._initBuildHash ({{root}}/node_modules/webpack/lib/NormalModule.js:417:16) {',
      "  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],",
      "  library: 'digital envelope routines',",
      "  reason: 'unsupported',",
      "  code: 'ERR_OSSL_EVP_UNSUPPORTED'",
      '}',
      '',
      'Node.js v20.11.1',
    ].join('\n'),
    cause: 'webpack 4 hashes modules with MD4, which OpenSSL 3 (bundled since Node 17) no longer enables by default.',
    fix: 'npm install --save-dev webpack@5',
    why: 'webpack 5 (and react-scripts 5) use a hash that works on OpenSSL 3. As a temporary workaround set `NODE_OPTIONS=--openssl-legacy-provider`.',
    prevent: 'Upgrade build tooling when moving to a new Node major version.',
    keywords: ['webpack', 'OpenSSL', 'legacy-provider'],
  },
  {
    id: 'heap-oom-static',
    files: {},
    stderr: [
      '<--- Last few GCs --->',
      '[18244:0x5a3c000]    41012 ms: Mark-Compact 4049.1 (4130.5) -> 4033.7 (4134.2) MB, 1873.20 / 0.00 ms  (average mu = 0.112) allocation failure',
      '',
      'FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory',
      ' 1: 0xb8ced1 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]',
      ' 2: 0xf06250 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]',
      '',
      'Node.js v20.11.1',
    ].join('\n'),
    cause: 'The process used all of its V8 heap (~4 GB here). Typical causes are loading a whole large file or query result into memory, or a leak (growing caches, listeners, arrays).',
    fix: "import { createReadStream } from 'node:fs';\nimport { createInterface } from 'node:readline';\n\nfor await (const line of createInterface({ input: createReadStream(file) })) {\n  handle(line);\n}",
    why: 'Streaming processes data in chunks so memory stays flat; raising `--max-old-space-size` only delays the crash.',
    prevent: 'Profile with `node --inspect` heap snapshots and stream large inputs instead of buffering them.',
    keywords: ['stream', 'memory', 'max-old-space-size'],
  },
  {
    id: 'eacces-port-static',
    files: {},
    stderr: [
      'node:events:497',
      '      throw er; // Unhandled \'error\' event',
      '      ^',
      '',
      'Error: listen EACCES: permission denied 0.0.0.0:{{port}}',
      '    at Server.setupListenHandle [as _listen2] (node:net:1872:21)',
      '    at listenInCluster (node:net:1951:12)',
      '    at Server.listen (node:net:2063:7)',
      '    at Object.<anonymous> ({{root}}/src/server.js:12:8)',
      "  code: 'EACCES',",
      "  syscall: 'listen',",
      "  address: '0.0.0.0',",
      '  port: {{port}}',
      '}',
      '',
      'Node.js v20.11.1',
    ].join('\n'),
    cause: 'Ports below 1024 (here {{port}}) are privileged on Linux/macOS, so a normal user cannot bind them.',
    fix: 'app.listen(process.env.PORT ?? 3000);',
    why: 'Listen on a high port and put a reverse proxy (nginx, a load balancer) or port mapping in front for {{port}}.',
    prevent: 'Never run Node as root just to get a low port.',
    keywords: ['privileged', '1024', 'PORT'],
    vars: { port: ['80', '443'] },
  },
];
