import type { ReviewScenario } from '../types.js';

const lines = (...l: string[]) => l.join('\n') + '\n';

export const MORE_REVIEWS: ReviewScenario[] = [
  {
    id: 'clean-validated-input',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.post('/{{entity}}', async (req, res) => {", '  res.sendStatus(501);', '});'),
    after: lines(
      "router.post('/{{entity}}', async (req, res, next) => {",
      '  const parsed = schema.safeParse(req.body);',
      '  if (!parsed.success) return res.status(400).json(parsed.error.flatten());',
      '  try {',
      '    const doc = await {{Model}}.create(parsed.data);',
      '    return res.status(201).json(doc);',
      '  } catch (err) {',
      '    return next(err);',
      '  }',
      '});',
    ),
    issues: [],
    vars: { entity: ['orders', 'products', 'reviews'], Model: ['Order', 'Product', 'Review'] },
  },
  {
    id: 'clean-script-sync-fs',
    path: 'scripts/{{script}}.js',
    before: lines("import { readFileSync, writeFileSync } from 'node:fs';", ''),
    after: lines(
      "import { readFileSync, writeFileSync } from 'node:fs';",
      '',
      "const pkg = JSON.parse(readFileSync('package.json', 'utf8'));",
      'pkg.version = process.argv[2];',
      "writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\\n');",
      "console.log(`version set to ${pkg.version}`);",
    ),
    issues: [],
    vars: { script: ['set-version', 'bump', 'release-prep'] },
  },
  {
    id: 'clean-awaited-save',
    path: 'src/services/{{svc}}.js',
    before: lines('export async function rename(id, name) {', '  const doc = await {{Model}}.findById(id);', '  doc.name = name;', '}'),
    after: lines('export async function rename(id, name) {', '  const doc = await {{Model}}.findById(id);', "  if (!doc) throw new NotFoundError('{{Model}}', id);", '  doc.name = name;', '  await doc.save();', '  return doc;', '}'),
    issues: [],
    vars: { svc: ['teams', 'projects', 'boards'], Model: ['Team', 'Project', 'Board'] },
  },
  {
    id: 'clean-catch-logged',
    path: 'src/jobs/{{job}}.js',
    before: lines('export async function run() {', '  await {{job}}();', '}'),
    after: lines(
      'export async function run() {',
      '  try {',
      '    await {{job}}();',
      '  } catch (err) {',
      "    logger.error({ err }, '{{job}} failed');",
      '    throw err;',
      '  }',
      '}',
    ),
    issues: [],
    vars: { job: ['rebuildIndex', 'sendReminders', 'expireTokens'] },
  },
  {
    id: 'clean-then-catch',
    path: 'src/index.js',
    before: lines("import { start } from './server.js';", ''),
    after: lines("import { start } from './server.js';", '', 'start()', "  .then(() => console.info('listening'))", '  .catch((err) => {', '    console.error(err);', '    process.exit(1);', '  });'),
    issues: [],
  },
  {
    id: 'clean-refactor-rename',
    path: 'src/utils/{{file}}.js',
    before: lines('export function fmt(n) {', "  return n.toFixed(2) + ' EUR';", '}'),
    after: lines("export function formatPrice(amount, currency = 'EUR') {", "  return new Intl.NumberFormat('en', { style: 'currency', currency }).format(amount);", '}'),
    issues: [],
    vars: { file: ['money', 'format', 'price'] },
  },
  {
    id: 'clean-test-file',
    path: 'test/{{name}}.test.js',
    before: lines("import { test } from 'node:test';", "import assert from 'node:assert/strict';"),
    after: lines(
      "import { test } from 'node:test';",
      "import assert from 'node:assert/strict';",
      "import { {{fn}} } from '../src/{{name}}.js';",
      '',
      "test('{{fn}} handles empty input', () => {",
      "  assert.equal({{fn}}(''), '');",
      '});',
    ),
    issues: [],
    vars: { name: ['slug', 'strings', 'text'], fn: ['slugify', 'capitalize', 'truncate'] },
  },
  {
    id: 'clean-config-default',
    path: 'src/config.js',
    before: lines('export const config = {', '  port: Number(process.env.PORT ?? 3000),', '};'),
    after: lines('export const config = {', '  port: Number(process.env.PORT ?? 3000),', "  logLevel: process.env.LOG_LEVEL ?? 'info',", '  {{key}}: Number(process.env.{{ENV}} ?? {{def}}),', '};'),
    issues: [],
    vars: { key: ['requestTimeoutMs', 'maxBodyKb', 'poolSize'], ENV: ['REQUEST_TIMEOUT_MS', 'MAX_BODY_KB', 'DB_POOL_SIZE'], def: ['10000', '100', '10'] },
  },
  {
    id: 'clean-pipeline-stream',
    path: 'src/export.js',
    before: lines("import { createWriteStream } from 'node:fs';", ''),
    after: lines(
      "import { createReadStream, createWriteStream } from 'node:fs';",
      "import { pipeline } from 'node:stream/promises';",
      "import { createGzip } from 'node:zlib';",
      '',
      'export async function compress(src, dest) {',
      '  await pipeline(createReadStream(src), createGzip(), createWriteStream(dest));',
      '}',
    ),
    issues: [],
  },
  {
    id: 'clean-console-in-dev-script',
    path: 'scripts/{{s}}.js',
    before: lines("import { db } from '../src/db.js';"),
    after: lines("import { db } from '../src/db.js';", '', 'const rows = await db.query({{q}});', 'console.log(`seeded ${rows.length} rows`);', 'await db.end();'),
    issues: [],
    vars: { s: ['seed', 'reset-db', 'fixtures'], q: ["'SELECT * FROM users'", "'SELECT id FROM orders'", "'SELECT 1'"] },
  },
  {
    id: 'clean-parameterized-insert',
    path: 'src/db/{{table}}.js',
    before: lines('export async function add{{Name}}(data) {', '  return null;', '}'),
    after: lines(
      'export async function add{{Name}}({ name, email }) {',
      '  const { rows } = await pool.query(',
      "    'INSERT INTO {{table}} (name, email) VALUES ($1, $2) RETURNING id',",
      '    [name, email],',
      '  );',
      '  return rows[0].id;',
      '}',
    ),
    issues: [],
    vars: { table: ['customers', 'members', 'leads'], Name: ['Customer', 'Member', 'Lead'] },
  },
  {
    id: 'clean-bounded-cache',
    path: 'src/cache.js',
    before: lines('const cache = new Map();'),
    after: lines("import { LRUCache } from 'lru-cache';", '', 'export const cache = new LRUCache({ max: {{max}}, ttl: 60_000 });'),
    issues: [],
    vars: { max: ['500', '1000', '5000'] },
  },
  {
    id: 'missing-await-in-loop-delete',
    path: 'src/services/cleanup.js',
    before: lines('export async function purge(ids) {', '  return ids.length;', '}'),
    after: lines('export async function purge(ids) {', '  for (const id of ids) {', '    {{Model}}.deleteOne({ _id: id });', '  }', '  return ids.length;', '}'),
    issues: [{ match: '.deleteOne({ _id: id });', severity: 'high', problem: '`deleteOne` is not awaited, so `purge` returns before deletions finish and failures are lost', fix: '`await {{Model}}.deleteOne({ _id: id });` (or `await {{Model}}.deleteMany({ _id: { $in: ids } })`)' }],
    vars: { Model: ['Session', 'Upload', 'Token'] },
  },
  {
    id: 'open-redirect',
    path: 'src/routes/login.js',
    before: lines("router.get('/login/done', (req, res) => {", "  res.redirect('/');", '});'),
    after: lines("router.get('/login/done', (req, res) => {", '  res.redirect(req.query.{{param}});', '});'),
    issues: [{ match: 'res.redirect(req.query', severity: 'high', problem: 'redirecting to an unvalidated query parameter is an open redirect that attackers can use for phishing', fix: "only allow relative paths: `const to = String(req.query.{{param}} ?? '/'); res.redirect(to.startsWith('/') && !to.startsWith('//') ? to : '/');`" }],
    vars: { param: ['next', 'returnTo', 'redirect'] },
  },
];
