import type { ReviewScenario } from '../types.js';

const lines = (...l: string[]) => l.join('\n') + '\n';

export const HIDDEN_BUGS: ReviewScenario[] = [
  {
    id: 'map-missing-return',
    path: 'src/services/{{svc}}.js',
    before: lines('export function withTax(items) {', '  return items;', '}'),
    after: lines('export function withTax(items) {', '  return items.map((item) => {', '    { ...item, total: item.price * {{rate}} };', '  });', '}'),
    issues: [{ match: 'return items.map((item) => {', severity: 'high', problem: 'the arrow function has a block body with no `return`, so `map` produces an array of `undefined`', fix: 'return the object: `items.map((item) => ({ ...item, total: item.price * {{rate}} }))`' }],
    vars: { svc: ['cart', 'invoice', 'quote'], rate: ['1.2', '1.19', '1.07'] },
  },
  {
    id: 'assignment-in-condition',
    path: 'src/middleware/{{mw}}.js',
    before: lines('export function {{mw}}(req, res, next) {', '  next();', '}'),
    after: lines('export function {{mw}}(req, res, next) {', "  if (req.user.role = '{{role}}') return next();", "  res.status(403).json({ error: 'forbidden' });", '}'),
    issues: [{ match: "if (req.user.role = '", severity: 'high', problem: '`=` assigns instead of comparing, so every user becomes {{role}} and the check always passes', fix: "use strict equality: `if (req.user.role === '{{role}}')`" }],
    vars: { mw: ['requireAdmin', 'requireOwner', 'requireStaff'], role: ['admin', 'owner', 'staff'] },
  },
  {
    id: 'callback-err-ignored',
    path: 'src/routes/assets.js',
    before: lines("router.get('/assets/:name', (req, res) => {", '  res.sendStatus(501);', '});'),
    after: lines("router.get('/assets/:name', (req, res) => {", '  fs.readFile(assetPath(req.params.name), (err, data) => {', '    res.type({{type}}).send(data);', '  });', '});'),
    issues: [{ match: 'fs.readFile(assetPath(', severity: 'medium', problem: 'the callback ignores `err`, so a missing file sends an empty 200 response instead of 404', fix: "check it first: `if (err) return res.sendStatus(err.code === 'ENOENT' ? 404 : 500);`" }],
    vars: { type: ["'png'", "'css'", "'svg'"] },
  },
  {
    id: 'pagination-off-by-one',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.get('/{{entity}}', async (req, res) => {", '  res.json(await {{Model}}.find().limit(20));', '});'),
    after: lines(
      "router.get('/{{entity}}', async (req, res) => {",
      '  const page = Math.max(1, Number(req.query.page) || 1);',
      '  const limit = 20;',
      '  res.json(await {{Model}}.find().skip(page * limit).limit(limit));',
      '});',
    ),
    issues: [{ match: '.skip(page * limit)', severity: 'medium', problem: 'pages start at 1, so `page * limit` skips the first 20 items and page 1 returns the second page', fix: '`.skip((page - 1) * limit)`' }],
    vars: { entity: ['articles', 'events', 'tickets'], Model: ['Article', 'Event', 'Ticket'] },
  },
  {
    id: 'check-then-create-race',
    path: 'src/services/signup.js',
    before: lines('export async function signup({ email, password }) {', '  return null;', '}'),
    after: lines(
      'export async function signup({ email, password }) {',
      '  if (await User.exists({ email })) throw new ConflictError(email);',
      '  return User.create({ email, password: await hash(password) });',
      '}',
    ),
    issues: [{ match: 'if (await User.exists({ email }))', severity: 'medium', problem: 'check-then-create is racy: two concurrent signups with the same email both pass the check and create duplicates', fix: 'add a unique index on `email` and handle the duplicate-key error (code 11000) instead of checking first' }],
  },
  {
    id: 'timing-unsafe-compare',
    path: 'src/webhooks/{{provider}}.js',
    before: lines("import crypto from 'node:crypto';", ''),
    after: lines(
      "import crypto from 'node:crypto';",
      '',
      'export function verify(body, signature) {',
      "  const expected = crypto.createHmac('sha256', process.env.{{ENV}}).update(body).digest('hex');",
      '  return signature === expected;',
      '}',
    ),
    issues: [{ match: 'return signature === expected;', severity: 'medium', problem: '`===` on signatures leaks timing information that helps attackers forge them', fix: "`crypto.timingSafeEqual(Buffer.from(signature, 'hex'), Buffer.from(expected, 'hex'))` after checking equal lengths" }],
    vars: { provider: ['stripe', 'github', 'shopify'], ENV: ['STRIPE_WEBHOOK_SECRET', 'GITHUB_WEBHOOK_SECRET', 'SHOPIFY_SECRET'] },
  },
  {
    id: 'math-random-token',
    path: 'src/auth/{{file}}.js',
    before: lines('export function createResetToken() {', '  return null;', '}'),
    after: lines('export function createResetToken() {', '  return Math.random().toString(36).slice(2);', '}'),
    issues: [{ match: 'Math.random().toString(36)', severity: 'high', problem: '`Math.random()` is not cryptographically secure, so reset tokens can be predicted', fix: "`crypto.randomBytes(32).toString('hex')` (or `crypto.randomUUID()`)" }],
    vars: { file: ['reset', 'tokens', 'magic-link'] },
  },
  {
    id: 'numeric-sort',
    path: 'src/stats/{{file}}.js',
    before: lines('export function median(values) {', '  return values[0];', '}'),
    after: lines('export function median(values) {', '  const sorted = [...values].sort();', '  return sorted[Math.floor(sorted.length / 2)];', '}'),
    issues: [{ match: 'const sorted = [...values].sort();', severity: 'medium', problem: '`sort()` without a comparator sorts numbers as strings (10 comes before 9), so the median is wrong', fix: '`[...values].sort((a, b) => a - b)`' }],
    vars: { file: ['latency', 'scores', 'prices'] },
  },
  {
    id: 'setinterval-async-overlap',
    path: 'src/workers/{{w}}.js',
    before: lines('export function startWorker() {', '  return null;', '}'),
    after: lines('export function startWorker() {', '  setInterval(async () => {', '    await {{op}}();', '  }, {{ms}});', '}'),
    issues: [{ match: 'setInterval(async () => {', severity: 'medium', problem: 'if `{{op}}` takes longer than the interval, runs overlap, and a rejection becomes an unhandled rejection that can crash the process', fix: 'schedule the next run after the previous one finishes (`setTimeout` loop) and wrap the body in try/catch' }],
    vars: { w: ['sync', 'poller', 'reindex'], op: ['syncOrders', 'pollQueue', 'reindexSearch'], ms: ['5000', '1000', '60000'] },
  },
  {
    id: 'md5-password',
    path: 'src/auth/password.js',
    before: lines("import crypto from 'node:crypto';", ''),
    after: lines("import crypto from 'node:crypto';", '', 'export function hashPassword(password) {', "  return crypto.createHash('{{algo}}').update(password).digest('hex');", '}'),
    issues: [{ match: "crypto.createHash('", severity: 'high', problem: 'a fast unsalted {{algo}} hash is unsafe for passwords; leaked hashes can be brute-forced quickly', fix: 'use a slow salted KDF: `crypto.scrypt` / `argon2` / `bcrypt`' }],
    vars: { algo: ['md5', 'sha1', 'sha256'] },
  },
  {
    id: 'middleware-missing-return-next',
    path: 'src/middleware/{{mw}}.js',
    before: lines('export function {{mw}}(req, res, next) {', '  next();', '}'),
    after: lines('export function {{mw}}(req, res, next) {', '  if (!req.headers[{{header}}]) {', '    res.status(401).end();', '  }', '  next();', '}'),
    issues: [{ match: 'res.status(401).end();', severity: 'high', problem: 'after sending 401 the middleware still calls `next()`, so unauthenticated requests reach the route', fix: '`return res.status(401).end();`' }],
    vars: { mw: ['requireApiKey', 'requireSession', 'requireToken'], header: ["'x-api-key'", "'cookie'", "'authorization'"] },
  },
  {
    id: 'date-month-off-by-one',
    path: 'src/billing/{{file}}.js',
    before: lines('export function periodStart(year, month) {', '  return null;', '}'),
    after: lines('export function periodStart(year, month) {', '  return new Date(Date.UTC(year, month, 1));', '}'),
    issues: [{ match: 'new Date(Date.UTC(year, month, 1))', severity: 'medium', problem: 'JavaScript months are 0-based, so passing a 1-based `month` returns the start of the following month', fix: '`new Date(Date.UTC(year, month - 1, 1))`' }],
    vars: { file: ['periods', 'invoices', 'cycles'] },
  },
];
