import type { ReviewScenario } from '../types.js';

const lines = (...l: string[]) => l.join('\n') + '\n';

export const REVIEWS: ReviewScenario[] = [
  {
    id: 'missing-await-save',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.post('/{{entity}}', async (req, res) => {", '  const doc = new {{Model}}(req.body);', '  res.status(201).json(doc);', '});'),
    after: lines("router.post('/{{entity}}', async (req, res) => {", '  const doc = new {{Model}}(req.body);', '  doc.save();', '  res.status(201).json(doc);', '});'),
    issues: [{ match: 'doc.save();', severity: 'high', problem: '`doc.save()` returns a promise that is not awaited; save errors are lost and 201 is sent before the write completes', fix: '`await doc.save();`' }],
    vars: { entity: ['orders', 'users', 'invoices'], Model: ['Order', 'User', 'Invoice'] },
  },
  {
    id: 'sql-injection',
    path: 'src/db/{{table}}.js',
    before: lines('export async function find{{Name}}(id) {', '  return null;', '}'),
    after: lines('export async function find{{Name}}(id) {', '  const { rows } = await pool.query(`SELECT * FROM {{table}} WHERE id = ${id}`);', '  return rows[0];', '}'),
    issues: [{ match: 'pool.query(`SELECT', severity: 'high', problem: 'SQL is built by interpolating `id`, which allows SQL injection', fix: "use a parameterized query: `pool.query('SELECT * FROM {{table}} WHERE id = $1', [id])`" }],
    vars: { table: ['users', 'products', 'accounts'], Name: ['User', 'Product', 'Account'] },
  },
  {
    id: 'command-injection',
    path: 'src/services/convert.js',
    before: lines("import { exec } from 'node:child_process';", ''),
    after: lines(
      "import { exec } from 'node:child_process';",
      '',
      'export function {{fn}}(file, cb) {',
      '  exec(`ffmpeg -i ${file} out.mp4`, cb);',
      '}',
    ),
    issues: [{ match: 'exec(`ffmpeg', severity: 'high', problem: '`exec` runs a shell with the user-controlled `file` interpolated, allowing command injection', fix: "use `execFile('ffmpeg', ['-i', file, 'out.mp4'], cb)`, which passes arguments without a shell" }],
    vars: { fn: ['convert', 'transcode', 'toMp4'] },
  },
  {
    id: 'path-traversal',
    path: 'src/routes/files.js',
    before: lines("import { join } from 'node:path';", ''),
    after: lines(
      "import { join } from 'node:path';",
      '',
      "app.get('/{{route}}/:name', (req, res) => {",
      "  res.sendFile(join(process.cwd(), 'uploads', req.params.name));",
      '});',
    ),
    issues: [{ match: 'res.sendFile(join(', severity: 'high', problem: '`req.params.name` is joined into a filesystem path unchecked; `../` sequences allow reading arbitrary files (path traversal)', fix: "use `res.sendFile(req.params.name, { root: uploadsDir })` or verify the resolved path starts with the uploads directory" }],
    vars: { route: ['download', 'files', 'attachments'] },
  },
  {
    id: 'hardcoded-secret',
    path: 'src/config.js',
    before: lines('export const config = {', '  port: process.env.PORT ?? 3000,', '};'),
    after: lines('export const config = {', '  port: process.env.PORT ?? 3000,', "  {{key}}: '{{value}}',", '};'),
    issues: [{ match: "{{key}}: '", severity: 'high', problem: 'a secret is hard-coded in source and will be committed to git', fix: 'read it from the environment (`process.env.{{ENV}}`) and rotate the leaked value' }],
    vars: { key: ['stripeKey', 'jwtSecret', 'apiToken'], value: ['sk_live_51HxQ2pLk9aZ', 'super-secret-signing-key', 'ghp_9f8d7c6b5a4e3d2c1b'], ENV: ['STRIPE_KEY', 'JWT_SECRET', 'API_TOKEN'] },
  },
  {
    id: 'tls-disabled',
    path: 'src/clients/{{svc}}.js',
    before: lines("import https from 'node:https';", ''),
    after: lines("import https from 'node:https';", '', 'export const agent = new https.Agent({ rejectUnauthorized: false });'),
    issues: [{ match: 'rejectUnauthorized: false', severity: 'high', problem: 'TLS certificate verification is disabled, exposing traffic to man-in-the-middle attacks', fix: 'remove the option; for a private CA pass `ca: readFileSync(caPath)` instead' }],
    vars: { svc: ['payments', 'billing', 'crm'] },
  },
  {
    id: 'sync-fs-in-handler',
    path: 'src/routes/report.js',
    before: lines("app.get('/report', async (req, res) => {", "  res.json({ ok: true });", '});'),
    after: lines("app.get('/report', async (req, res) => {", "  const template = fs.readFileSync('./templates/{{tpl}}.html', 'utf8');", '  res.send(render(template, req.query));', '});'),
    issues: [{ match: 'fs.readFileSync(', severity: 'medium', problem: '`readFileSync` blocks the event loop on every request', fix: "read the template once at startup, or use `await fs.promises.readFile(...)`" }],
    vars: { tpl: ['report', 'invoice', 'summary'] },
  },
  {
    id: 'empty-catch',
    path: 'src/jobs/{{job}}.js',
    before: lines('export async function run() {', '  await {{job}}();', '}'),
    after: lines('export async function run() {', '  try {', '    await {{job}}();', '  } catch (e) {}', '}'),
    issues: [{ match: 'catch (e) {}', severity: 'medium', problem: 'the empty catch silently swallows failures of `{{job}}()`', fix: 'log the error and rethrow or report it: `catch (err) { logger.error(err); throw err; }`' }],
    vars: { job: ['syncInventory', 'sendDigest', 'cleanupSessions'] },
  },
  {
    id: 'then-without-catch',
    path: 'src/index.js',
    before: lines("import { connect } from './db.js';", ''),
    after: lines("import { connect } from './db.js';", '', 'connect().then(() => {', "  console.info('{{msg}}');", '});'),
    issues: [{ match: 'connect().then(', severity: 'high', problem: 'the promise chain has no `.catch`, so a connection failure becomes an unhandled rejection that crashes the process', fix: "add `.catch((err) => { console.error(err); process.exit(1); })`, or `await connect()` inside try/catch" }],
    vars: { msg: ['db connected', 'database ready', 'connected'] },
  },
  {
    id: 'foreach-async',
    path: 'src/services/notify.js',
    before: lines('export async function notifyAll(users) {', '  return users.length;', '}'),
    after: lines('export async function notifyAll(users) {', '  users.forEach(async (u) => {', '    await {{send}}(u.email);', '  });', "  return 'done';", '}'),
    issues: [{ match: 'users.forEach(async', severity: 'high', problem: '`forEach` does not wait for async callbacks, so `notifyAll` returns before any {{send}} finishes and their errors are unhandled', fix: '`await Promise.all(users.map((u) => {{send}}(u.email)))` or a `for...of` loop with `await`' }],
    vars: { send: ['sendEmail', 'sendSms', 'pushNotification'] },
  },
  {
    id: 'eval-user-input',
    path: 'src/routes/calc.js',
    before: lines("router.post('/calc', (req, res) => {", '  res.json({ result: null });', '});'),
    after: lines("router.post('/calc', (req, res) => {", '  const result = eval(req.body.{{field}});', '  res.json({ result });', '});'),
    issues: [{ match: 'eval(req.body', severity: 'high', problem: '`eval` on request input lets any client run arbitrary code on the server', fix: 'parse the expression with a safe evaluator (e.g. `mathjs` `evaluate` with a limited scope) or a whitelist' }],
    vars: { field: ['expression', 'formula', 'expr'] },
  },
  {
    id: 'missing-return-after-send',
    path: 'src/routes/auth.js',
    before: lines("router.get('/me', (req, res) => {", '  res.json(req.user);', '});'),
    after: lines("router.get('/me', (req, res) => {", '  if (!req.user) {', "    res.status(401).json({ error: 'unauthorized' });", '  }', '  res.json(req.user);', '});'),
    issues: [{ match: "res.status(401)", severity: 'high', problem: 'the handler does not return after sending 401, so `res.json(req.user)` also runs and throws ERR_HTTP_HEADERS_SENT', fix: "`return res.status(401).json({ error: 'unauthorized' });`" }],
  },
  {
    id: 'console-log-secret',
    path: 'src/auth/login.js',
    before: lines('export async function login({ email, password }) {', '  const user = await users.findByEmail(email);', '  return verify(user, password);', '}'),
    after: lines('export async function login({ email, password }) {', '  console.log(`login attempt ${email} ${password}`);', '  const user = await users.findByEmail(email);', '  return verify(user, password);', '}'),
    issues: [{ match: 'console.log(`login attempt', severity: 'high', problem: 'the plaintext password is written to logs', fix: 'never log credentials; log only the email or a request id' }],
  },
  {
    id: 'unbounded-body',
    path: 'src/server.js',
    before: lines("import express from 'express';", 'const app = express();'),
    after: lines("import express from 'express';", 'const app = express();', "app.use(express.json({ limit: '{{limit}}' }));"),
    issues: [{ match: 'express.json({ limit', severity: 'medium', problem: "a {{limit}} JSON body limit lets clients send huge payloads that are parsed in memory (DoS risk)", fix: "keep the default (100kb) or a small limit such as `'1mb'`, and use streaming uploads for large files" }],
    vars: { limit: ['500mb', '1gb', '200mb'] },
  },
  {
    id: 'promise-all-no-catch-loop',
    path: 'src/workers/{{w}}.js',
    before: lines('export async function handle(batch) {', '  return batch;', '}'),
    after: lines('export async function handle(batch) {', '  for (const item of batch) {', '    await {{op}}(item);', '  }', '}'),
    issues: [],
    vars: { w: ['import', 'resize', 'billing'], op: ['importRow', 'resizeImage', 'chargeCard'] },
  },
  {
    id: 'clean-param-query',
    path: 'src/db/{{table}}.js',
    before: lines('export async function get{{Name}}(id) {', '  return null;', '}'),
    after: lines("export async function get{{Name}}(id) {", "  const { rows } = await pool.query('SELECT * FROM {{table}} WHERE id = $1', [id]);", '  return rows[0] ?? null;', '}'),
    issues: [],
    vars: { table: ['orders', 'teams', 'events'], Name: ['Order', 'Team', 'Event'] },
  },
  {
    id: 'clean-await-try',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.delete('/{{entity}}/:id', async (req, res) => {", '  res.sendStatus(204);', '});'),
    after: lines(
      "router.delete('/{{entity}}/:id', async (req, res, next) => {",
      '  try {',
      '    await {{Model}}.deleteOne({ _id: req.params.id });',
      '    res.sendStatus(204);',
      '  } catch (err) {',
      '    next(err);',
      '  }',
      '});',
    ),
    issues: [],
    vars: { entity: ['posts', 'comments', 'tags'], Model: ['Post', 'Comment', 'Tag'] },
  },
  {
    id: 'clean-startup-readfilesync',
    path: 'src/templates.js',
    before: lines("import { readFileSync } from 'node:fs';", ''),
    after: lines("import { readFileSync } from 'node:fs';", '', "export const layout = readFileSync(new URL('./{{tpl}}.html', import.meta.url), 'utf8');"),
    issues: [],
    vars: { tpl: ['layout', 'email', 'base'] },
  },
  {
    id: 'clean-cli-console',
    path: 'bin/{{cli}}.js',
    before: lines('#!/usr/bin/env node', "import { run } from '../src/index.js';"),
    after: lines('#!/usr/bin/env node', "import { run } from '../src/index.js';", '', 'const code = await run(process.argv.slice(2));', "console.log(code === 0 ? 'done' : 'failed');", 'process.exitCode = code;'),
    issues: [],
    vars: { cli: ['migrate', 'seed', 'build'] },
  },
  {
    id: 'clean-execfile',
    path: 'src/git.js',
    before: lines("import { execFile } from 'node:child_process';", "import { promisify } from 'node:util';"),
    after: lines(
      "import { execFile } from 'node:child_process';",
      "import { promisify } from 'node:util';",
      '',
      'const run = promisify(execFile);',
      '',
      'export async function {{fn}}(ref) {',
      "  const { stdout } = await run('git', ['log', '--oneline', ref]);",
      '  return stdout.trim().split(\'\\n\');',
      '}',
    ),
    issues: [],
    vars: { fn: ['commitsSince', 'history', 'logFor'] },
  },
  {
    id: 'clean-env-config',
    path: 'src/config.js',
    before: lines('export const config = {', '  port: 3000,', '};'),
    after: lines('export const config = {', '  port: Number(process.env.PORT ?? 3000),', '  {{key}}: process.env.{{ENV}},', '};'),
    issues: [],
    vars: { key: ['databaseUrl', 'redisUrl', 'jwtSecret'], ENV: ['DATABASE_URL', 'REDIS_URL', 'JWT_SECRET'] },
  },
  {
    id: 'mixed-await-and-leak',
    path: 'src/services/{{svc}}.js',
    before: lines('const cache = new Map();', '', 'export async function get(id) {', '  return cache.get(id);', '}'),
    after: lines(
      'const cache = new Map();',
      '',
      'export async function get(id) {',
      '  if (cache.has(id)) return cache.get(id);',
      '  const value = await fetch{{Name}}(id);',
      '  cache.set(id, value);',
      '  return value;',
      '}',
    ),
    issues: [{ match: 'cache.set(id, value);', severity: 'medium', problem: 'the Map cache has no size limit or expiry, so memory grows with every distinct id', fix: 'use an LRU with a max size/TTL (e.g. `lru-cache`)' }],
    vars: { svc: ['profiles', 'prices', 'geo'], Name: ['Profile', 'Price', 'Location'] },
  },
  {
    id: 'parseint-radix-and-nan',
    path: 'src/routes/page.js',
    before: lines("router.get('/items', async (req, res) => {", '  res.json(await Item.find().limit(20));', '});'),
    after: lines(
      "router.get('/items', async (req, res) => {",
      '  const limit = parseInt(req.query.limit);',
      '  res.json(await Item.find().limit(limit));',
      '});',
    ),
    issues: [{ match: 'parseInt(req.query.limit)', severity: 'medium', problem: 'missing or invalid `limit` becomes NaN and there is no upper bound, so clients can request unlimited rows', fix: '`const limit = Math.min(Number.parseInt(req.query.limit, 10) || 20, 100);`' }],
  },
  {
    id: 'jwt-none-verify',
    path: 'src/auth/token.js',
    before: lines("import jwt from 'jsonwebtoken';", ''),
    after: lines("import jwt from 'jsonwebtoken';", '', 'export function readToken(token) {', '  return jwt.decode(token);', '}'),
    issues: [{ match: 'jwt.decode(token)', severity: 'high', problem: '`jwt.decode` does not verify the signature, so anyone can forge a token', fix: "`jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] })`" }],
  },
  {
    id: 'cors-wildcard-credentials',
    path: 'src/server.js',
    before: lines("import cors from 'cors';", ''),
    after: lines("import cors from 'cors';", '', 'app.use(cors({ origin: true, credentials: true }));'),
    issues: [{ match: 'origin: true, credentials: true', severity: 'high', problem: 'reflecting any origin while allowing credentials lets every website make authenticated requests as the user', fix: "use an allowlist: `cors({ origin: ['https://app.example.com'], credentials: true })`" }],
  },
];
