import type { ReviewScenario } from '../types.js';

const lines = (...l: string[]) => l.join('\n') + '\n';

export const TS_REVIEWS: ReviewScenario[] = [
  {
    id: 'prisma-client-per-request',
    path: 'src/routes/{{entity}}.ts',
    before: lines("import { Router } from 'express';", 'export const router = Router();'),
    after: lines(
      "import { Router } from 'express';",
      "import { PrismaClient } from '@prisma/client';",
      'export const router = Router();',
      '',
      "router.get('/{{entity}}', async (_req, res) => {",
      '  const prisma = new PrismaClient();',
      '  res.json(await prisma.{{model}}.findMany());',
      '});',
    ),
    issues: [{ match: 'const prisma = new PrismaClient();', severity: 'high', problem: 'a new PrismaClient (with its own connection pool) is created on every request and never disconnected, which quickly exhausts database connections', fix: 'create one shared client at module level (or a NestJS PrismaService) and reuse it' }],
    vars: { entity: ['users', 'posts', 'orders'], model: ['user', 'post', 'order'] },
  },
  {
    id: 'prisma-n-plus-one',
    path: 'src/services/{{svc}}.ts',
    before: lines('export async function listAuthors() {', '  return prisma.author.findMany();', '}'),
    after: lines(
      'export async function listAuthors() {',
      '  const authors = await prisma.author.findMany();',
      '  for (const a of authors) {',
      '    a.{{rel}} = await prisma.{{child}}.findMany({ where: { authorId: a.id } });',
      '  }',
      '  return authors;',
      '}',
    ),
    issues: [{ match: 'await prisma.{{child}}.findMany({ where: { authorId', severity: 'medium', problem: 'one extra query per author (N+1 queries), which gets slow as the table grows', fix: "load the relation in one query: `prisma.author.findMany({ include: { {{rel}}: true } })`" }],
    vars: { svc: ['authors', 'blog', 'catalog'], rel: ['posts', 'books', 'articles'], child: ['post', 'book', 'article'] },
  },
  {
    id: 'prisma-raw-unsafe-injection',
    path: 'src/repositories/{{repo}}.ts',
    before: lines('export async function search(term: string) {', '  return [];', '}'),
    after: lines('export async function search(term: string) {', '  return prisma.$queryRawUnsafe(`SELECT * FROM {{table}} WHERE name ILIKE \'%${term}%\'`);', '}'),
    issues: [{ match: 'prisma.$queryRawUnsafe(`', severity: 'high', problem: '`$queryRawUnsafe` with an interpolated search term allows SQL injection', fix: "use the tagged template, which parameterizes values: prisma.$queryRaw`SELECT * FROM {{table}} WHERE name ILIKE ${'%' + term + '%'}`" }],
    vars: { repo: ['products', 'users', 'places'], table: ['products', 'users', 'places'] },
  },
  {
    id: 'prisma-transaction-not-awaited',
    path: 'src/services/transfer.ts',
    before: lines('export async function transfer(from: string, to: string, amount: number) {', '  return null;', '}'),
    after: lines(
      'export async function transfer(from: string, to: string, amount: number) {',
      '  prisma.$transaction([',
      '    prisma.account.update({ where: { id: from }, data: { balance: { decrement: amount } } }),',
      '    prisma.account.update({ where: { id: to }, data: { balance: { increment: amount } } }),',
      '  ]);',
      "  return 'ok';",
      '}',
    ),
    issues: [{ match: 'prisma.$transaction([', severity: 'high', problem: 'the transaction promise is not awaited, so `transfer` reports success before the money moves and failures are unhandled', fix: '`await prisma.$transaction([...])`' }],
  },
  {
    id: 'prisma-clean-select',
    path: 'src/services/{{svc}}.ts',
    before: lines('export async function getProfile(id: string) {', '  return null;', '}'),
    after: lines(
      'export async function getProfile(id: string) {',
      '  const user = await prisma.user.findUnique({',
      '    where: { id },',
      '    select: { id: true, name: true, {{field}}: true },',
      '  });',
      "  if (!user) throw new NotFoundError('user', id);",
      '  return user;',
      '}',
    ),
    issues: [],
    vars: { svc: ['profiles', 'accounts', 'members'], field: ['avatarUrl', 'bio', 'createdAt'] },
  },
  {
    id: 'nest-res-decorator-hang',
    path: 'src/{{entity}}/{{entity}}.controller.ts',
    before: lines("@Controller('{{entity}}')", 'export class {{Ctrl}} {', '  constructor(private readonly service: {{Svc}}) {}', '}'),
    after: lines(
      "@Controller('{{entity}}')",
      'export class {{Ctrl}} {',
      '  constructor(private readonly service: {{Svc}}) {}',
      '',
      '  @Get()',
      '  findAll(@Res() res: Response) {',
      '    return this.service.findAll();',
      '  }',
      '}',
    ),
    issues: [{ match: 'findAll(@Res() res: Response) {', severity: 'high', problem: 'injecting `@Res()` switches Nest to manual mode, so the returned value is never sent and the request hangs', fix: 'remove `@Res()` and just return the data (or use `@Res({ passthrough: true })` if you need headers)' }],
    vars: { entity: ['users', 'orders', 'files'], Ctrl: ['UsersController', 'OrdersController', 'FilesController'], Svc: ['UsersService', 'OrdersService', 'FilesService'] },
  },
  {
    id: 'nest-generic-error-500',
    path: 'src/{{entity}}/{{entity}}.service.ts',
    before: lines('async findOne(id: number) {', '  return this.prisma.{{model}}.findUnique({ where: { id } });', '}'),
    after: lines(
      'async findOne(id: number) {',
      '  const item = await this.prisma.{{model}}.findUnique({ where: { id } });',
      "  if (!item) throw new Error('{{Model}} not found');",
      '  return item;',
      '}',
    ),
    issues: [{ match: "if (!item) throw new Error('", severity: 'medium', problem: 'a plain `Error` becomes a 500 Internal Server Error in Nest, although the client asked for something that does not exist', fix: '`throw new NotFoundException(`{{Model}} ${id} not found`)`' }],
    vars: { entity: ['posts', 'teams', 'events'], model: ['post', 'team', 'event'], Model: ['Post', 'Team', 'Event'] },
  },
  {
    id: 'return-without-await-in-try',
    path: 'src/{{entity}}/{{entity}}.service.ts',
    before: lines('async create(dto: Create{{Model}}Dto) {', '  return this.prisma.{{model}}.create({ data: dto });', '}'),
    after: lines(
      'async create(dto: Create{{Model}}Dto) {',
      '  try {',
      '    return this.prisma.{{model}}.create({ data: dto });',
      '  } catch (e) {',
      "    throw new BadRequestException('could not create {{model}}');",
      '  }',
      '}',
    ),
    issues: [{ match: '    return this.prisma.{{model}}.create({ data: dto });', severity: 'medium', problem: 'returning the promise without `await` inside try means its rejection happens after the function returns, so the catch block never runs', fix: '`return await this.prisma.{{model}}.create({ data: dto });`' }],
    vars: { entity: ['tags', 'notes', 'comments'], model: ['tag', 'note', 'comment'], Model: ['Tag', 'Note', 'Comment'] },
  },
  {
    id: 'nest-clean-controller',
    path: 'src/{{entity}}/{{entity}}.controller.ts',
    before: lines("@Controller('{{entity}}')", 'export class {{Ctrl}} {', '  constructor(private readonly service: {{Svc}}) {}', '}'),
    after: lines(
      "@Controller('{{entity}}')",
      'export class {{Ctrl}} {',
      '  constructor(private readonly service: {{Svc}}) {}',
      '',
      "  @Get(':id')",
      "  findOne(@Param('id', ParseIntPipe) id: number) {",
      '    return this.service.findOne(id);',
      '  }',
      '',
      '  @Post()',
      '  create(@Body() dto: Create{{Model}}Dto) {',
      '    return this.service.create(dto);',
      '  }',
      '}',
    ),
    issues: [],
    vars: { entity: ['projects', 'invoices', 'tickets'], Ctrl: ['ProjectsController', 'InvoicesController', 'TicketsController'], Svc: ['ProjectsService', 'InvoicesService', 'TicketsService'], Model: ['Project', 'Invoice', 'Ticket'] },
  },
  {
    id: 'nest-clean-module',
    path: 'src/{{name}}/{{name}}.module.ts',
    before: lines("import { Module } from '@nestjs/common';", '', '@Module({})', 'export class {{Mod}} {}'),
    after: lines(
      "import { Module } from '@nestjs/common';",
      "import { PrismaModule } from '../prisma/prisma.module';",
      "import { {{Svc}} } from './{{name}}.service';",
      '',
      '@Module({',
      '  imports: [PrismaModule],',
      '  providers: [{{Svc}}],',
      '  exports: [{{Svc}}],',
      '})',
      'export class {{Mod}} {}',
    ),
    issues: [],
    vars: { name: ['mail', 'billing', 'search'], Mod: ['MailModule', 'BillingModule', 'SearchModule'], Svc: ['MailService', 'BillingService', 'SearchService'] },
  },
  {
    id: 'ts-non-null-env',
    path: 'src/auth/jwt.ts',
    before: lines("import jwt from 'jsonwebtoken';", ''),
    after: lines("import jwt from 'jsonwebtoken';", '', 'export const sign = (payload: object) => jwt.sign(payload, process.env.{{ENV}}!, { expiresIn: \'1h\' });'),
    issues: [{ match: 'process.env.{{ENV}}!', severity: 'medium', problem: 'the `!` only silences TypeScript; if `{{ENV}}` is unset, signing fails at runtime on the first login instead of at startup', fix: 'validate required env vars at startup (e.g. zod) and export a typed config value' }],
    vars: { ENV: ['JWT_SECRET', 'TOKEN_SECRET', 'AUTH_SECRET'] },
  },
  {
    id: 'ts-as-any-cast',
    path: 'src/webhooks/{{provider}}.ts',
    before: lines('export function handle(body: unknown) {', '  return null;', '}'),
    after: lines('export function handle(body: unknown) {', '  const event = body as any;', '  return applyCredit(event.data.customer, event.data.amount);', '}'),
    issues: [{ match: 'const event = body as any;', severity: 'medium', problem: '`as any` skips all validation of an external webhook payload, so a malformed or malicious body reaches `applyCredit` unchecked', fix: 'parse it with a schema (e.g. `WebhookSchema.parse(body)`) and verify the webhook signature first' }],
    vars: { provider: ['stripe', 'paddle', 'lemonsqueezy'] },
  },
  {
    id: 'ts-clean-type-guard',
    path: 'src/utils/{{file}}.ts',
    before: lines('export function toMessage(err: unknown) {', '  return String(err);', '}'),
    after: lines('export function toMessage(err: unknown): string {', '  if (err instanceof Error) return err.message;', "  if (typeof err === 'string') return err;", '  return JSON.stringify(err);', '}'),
    issues: [],
    vars: { file: ['errors', 'messages', 'format'] },
  },
];
