import type { ReviewScenario } from '../types.js';

const lines = (...l: string[]) => l.join('\n') + '\n';

export const HINT_REVIEWS: ReviewScenario[] = [
  {
    id: 'jwt-decode-middleware',
    path: 'src/middleware/{{mw}}.js',
    before: lines('export function {{mw}}(req, res, next) {', '  next();', '}'),
    after: lines(
      'export function {{mw}}(req, res, next) {',
      "  const token = req.headers.authorization?.split(' ')[1];",
      '  req.user = jwt.decode(token);',
      '  next();',
      '}',
    ),
    issues: [{ match: 'req.user = jwt.decode(token);', severity: 'high', problem: '`jwt.decode` only base64-decodes the token without checking its signature, so anyone can forge `req.user`', fix: "`req.user = jwt.verify(token, process.env.JWT_SECRET, { algorithms: ['HS256'] })` inside try/catch, returning 401 on failure" }],
    vars: { mw: ['authenticate', 'requireUser', 'loadUser'] },
  },
  {
    id: 'foreach-async-save',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.post('/{{entity}}/close', async (req, res) => {", '  res.json({ ok: true });', '});'),
    after: lines(
      "router.post('/{{entity}}/close', async (req, res) => {",
      '  const open = await {{Model}}.find({ status: \'open\' });',
      '  open.forEach(async (doc) => {',
      "    doc.status = 'closed';",
      '    await doc.save();',
      '  });',
      '  res.json({ closed: open.length });',
      '});',
    ),
    issues: [{ match: 'open.forEach(async (doc) => {', severity: 'high', problem: '`forEach` ignores the promises from the async callback, so the response is sent before any save finishes and save errors are unhandled', fix: '`await Promise.all(open.map(async (doc) => { doc.status = \'closed\'; await doc.save(); }))` or `updateMany`' }],
    vars: { entity: ['tickets', 'orders', 'tasks'], Model: ['Ticket', 'Order', 'Task'] },
  },
  {
    id: 'n-plus-one-sql',
    path: 'src/services/{{svc}}.js',
    before: lines('export async function listOrders(userId) {', "  return db.query('SELECT * FROM orders WHERE user_id = $1', [userId]);", '}'),
    after: lines(
      'export async function listOrders(userId) {',
      "  const { rows: orders } = await db.query('SELECT * FROM orders WHERE user_id = $1', [userId]);",
      '  for (const order of orders) {',
      "    order.items = (await db.query('SELECT * FROM order_items WHERE order_id = $1', [order.id])).rows;",
      '  }',
      '  return orders;',
      '}',
    ),
    issues: [{ match: "order.items = (await db.query(", severity: 'medium', problem: 'one query per order (N+1), so a user with many orders triggers many round-trips', fix: "fetch all items at once: `SELECT * FROM order_items WHERE order_id = ANY($1)` with the order ids, then group them in memory" }],
    vars: { svc: ['orders', 'history', 'account'] },
  },
  {
    id: 'n-plus-one-mongoose',
    path: 'src/services/{{svc}}.js',
    before: lines('export async function members() {', '  return User.find();', '}'),
    after: lines(
      'export async function members() {',
      '  const users = await User.find().lean();',
      '  for (const u of users) {',
      '    u.{{rel}} = await {{Model}}.findById(u.{{rel}}Id).lean();',
      '  }',
      '  return users;',
      '}',
    ),
    issues: [{ match: 'await {{Model}}.findById(u.', severity: 'medium', problem: 'a separate `findById` per user (N+1 queries)', fix: "use `User.find().populate('{{rel}}')`, or load all ids with one `{{Model}}.find({ _id: { $in: ids } })`" }],
    vars: { svc: ['members', 'directory', 'staff'], rel: ['team', 'company', 'office'], Model: ['Team', 'Company', 'Office'] },
  },
  {
    id: 'parseint-page',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.get('/{{entity}}', async (req, res) => {", '  res.json(await {{Model}}.find().limit(20));', '});'),
    after: lines(
      "router.get('/{{entity}}', async (req, res) => {",
      '  const page = parseInt(req.query.page);',
      '  res.json(await {{Model}}.find().skip((page - 1) * 20).limit(20));',
      '});',
    ),
    issues: [{ match: 'const page = parseInt(req.query.page);', severity: 'medium', problem: 'a missing or non-numeric `page` becomes NaN (and 0 or negative values give a negative skip), which errors or returns wrong pages', fix: '`const page = Math.max(1, Number.parseInt(req.query.page, 10) || 1);`' }],
    vars: { entity: ['photos', 'invoices', 'logs'], Model: ['Photo', 'Invoice', 'Log'] },
  },
  {
    id: 'clean-loop-no-query',
    path: 'src/utils/{{file}}.js',
    before: lines('export function total(items) {', '  return 0;', '}'),
    after: lines('export function total(items) {', '  let sum = 0;', '  for (const item of items) {', '    sum += item.price * item.qty;', '  }', '  return sum;', '}'),
    issues: [],
    vars: { file: ['cart', 'totals', 'invoice'] },
  },
  {
    id: 'clean-loop-await-cleanup',
    path: 'scripts/{{s}}.js',
    before: lines("import { unlink } from 'node:fs/promises';", ''),
    after: lines("import { unlink } from 'node:fs/promises';", '', 'export async function removeAll(paths) {', '  for (const p of paths) {', '    await unlink(p);', '  }', '}'),
    issues: [],
    vars: { s: ['cleanup', 'purge-tmp', 'rotate-logs'] },
  },
  {
    id: 'clean-parseint-radix',
    path: 'src/routes/{{entity}}.js',
    before: lines("router.get('/{{entity}}/:id', async (req, res) => {", '  res.sendStatus(501);', '});'),
    after: lines(
      "router.get('/{{entity}}/:id', async (req, res) => {",
      '  const id = Number.parseInt(req.params.id, 10);',
      '  if (!Number.isInteger(id) || id < 1) return res.sendStatus(400);',
      '  const item = await {{Model}}.findByPk(id);',
      '  return item ? res.json(item) : res.sendStatus(404);',
      '});',
    ),
    issues: [],
    vars: { entity: ['books', 'albums', 'venues'], Model: ['Book', 'Album', 'Venue'] },
  },
];
